import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";

import { ArrowUpRightIcon, CheckIcon, PlayIcon } from "../components/icons";
import { PageHero } from "../components/page-hero";
import {
  loadReleaseSmokeData,
  readableReleaseSmokeMessage,
  releaseSmokeHistory,
  releaseSmokeScenarios,
  type ReleaseSmokeCase,
  type ReleaseSmokeData,
  type ReleaseSmokeRun,
  type ReleaseSmokeScenario,
} from "../release-smoke-data";
import { pageHead } from "../seo";

const description =
  "Codex and Claude create presentations from the same fixed briefs in clean projects. Compare every real conversation and generated result.";

export const Route = createFileRoute("/release-smoke")({
  component: ReleaseSmokePage,
  head: () => pageHead("Release smoke", description, "/release-smoke"),
});

const formatDate = (timestamp: string) =>
  new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "UTC",
  }).format(new Date(timestamp));

const formatDuration = (seconds: number) => {
  if (seconds === 0) return "Not measured";
  const minutes = Math.floor(seconds / 60);
  const remainder = seconds % 60;
  return minutes === 0 ? `${remainder}s` : `${minutes}m ${remainder}s`;
};

function RunStatus({ run }: { run: ReleaseSmokeRun }) {
  const passed = run.cases.every((scenario) => scenario.status === "passed");
  return (
    <span className="release-smoke__status" data-status={passed ? "passed" : "failed"}>
      <i aria-hidden="true" />
      {passed ? "Build verified" : "Build needs attention"}
    </span>
  );
}

function RunMetadata({ run }: { run: ReleaseSmokeRun }) {
  const providers = [...new Set(run.cases.map((scenario) => scenario.provider.label))];
  const metadata = [
    ["Package", `drever@${run.release.version}`],
    ["Release", run.release.commit.slice(0, 8)],
    ["Harness", run.harness.commit.slice(0, 8)],
    ["Generated", `${formatDate(run.generatedAt)} UTC`],
    ["Providers", providers.join(" · ")],
    ["Node", run.runner.nodeVersion],
  ];

  return (
    <dl className="release-smoke__metadata">
      {metadata.map(([term, value]) => (
        <div key={term}>
          <dt>{term}</dt>
          <dd>{value}</dd>
        </div>
      ))}
    </dl>
  );
}

function ProviderResult({ result, run }: { result: ReleaseSmokeCase; run: ReleaseSmokeRun }) {
  const headingId = `release-smoke-result-${result.id}`;
  const conversationId = `release-smoke-conversation-${result.id}`;

  return (
    <article
      aria-labelledby={headingId}
      className="release-smoke__result"
      data-header-tone="light"
      data-provider={result.provider.id}
    >
      <header className="release-smoke__result-heading">
        <div>
          <span>Generated by</span>
          <h3 id={headingId}>{result.provider.label}</h3>
        </div>
        <dl>
          <div>
            <dt>Model</dt>
            <dd>{result.provider.model}</dd>
          </div>
          <div>
            <dt>CLI</dt>
            <dd>{result.provider.version}</dd>
          </div>
        </dl>
      </header>

      <div className="release-smoke__stage" data-header-tone="dark">
        <iframe
          allowFullScreen
          key={`${run.id}:${result.id}`}
          loading="lazy"
          referrerPolicy="no-referrer"
          sandbox="allow-presentation allow-same-origin allow-scripts"
          src={`${result.deck.audience}index.html`}
          title={`${result.provider.label} result for ${result.title}`}
        />
      </div>

      <div className="release-smoke__actions">
        <a
          className="button button--primary"
          href={`${result.deck.audience}index.html`}
          rel="noreferrer"
          target="_blank"
        >
          <PlayIcon /> Open live deck
        </a>
        <a
          className="button button--quiet"
          href={`${result.deck.document}index.html`}
          rel="noreferrer"
          target="_blank"
        >
          Read document <ArrowUpRightIcon />
        </a>
        <a
          className="button button--quiet"
          href={result.deck.source}
          rel="noreferrer"
          target="_blank"
        >
          View MDX <ArrowUpRightIcon />
        </a>
      </div>

      <section aria-labelledby={conversationId} className="release-smoke__conversation">
        <header>
          <span>Conversation</span>
          <h4 id={conversationId}>The route to the result.</h4>
        </header>
        <ol>
          {result.messages.map((message, index) => (
            <li data-role={message.role} key={`${message.role}-${index}`}>
              <span>{message.role === "user" ? "User" : result.provider.label}</span>
              <p>{readableReleaseSmokeMessage(message.content)}</p>
            </li>
          ))}
        </ol>
      </section>

      <aside className="release-smoke__checks">
        <header>
          <span>Verification</span>
          <strong>
            {result.status === "passed"
              ? "Build and surfaces verified"
              : "Build verification failed"}
          </strong>
        </header>
        <ul>
          {result.checks.map((check) => (
            <li key={check}>
              <CheckIcon />
              {check}
            </li>
          ))}
        </ul>
        <dl>
          <div>
            <dt>Run time</dt>
            <dd>{formatDuration(result.durationSeconds)}</dd>
          </div>
          <div>
            <dt>Prompt</dt>
            <dd>
              <a href={run.runner.promptUrl}>prompt.md</a>
            </dd>
          </div>
        </dl>
      </aside>
    </article>
  );
}

function ScenarioComparison({
  run,
  scenario,
}: {
  run: ReleaseSmokeRun;
  scenario: ReleaseSmokeScenario;
}) {
  return (
    <section aria-labelledby="release-smoke-preview-title" className="release-smoke__preview">
      <header>
        <div>
          <span>{scenario.mode === "surprise-me" ? "Surprise me" : "Guided answers"}</span>
          <h2 id="release-smoke-preview-title">{scenario.title}</h2>
        </div>
        <div>
          <strong>One brief. Independent results.</strong>
          <p>{scenario.brief}</p>
        </div>
      </header>

      <div className="release-smoke__comparison">
        {scenario.results.map((result) => (
          <ProviderResult key={result.id} result={result} run={run} />
        ))}
      </div>
    </section>
  );
}

function EmptyReleaseSmokePage() {
  return (
    <main className="release-smoke" data-header-tone="light" id="main" tabIndex={-1}>
      <PageHero
        description={description}
        eyebrow="Built in public"
        title="Watch the prompt become a real deck."
      >
        <div className="release-smoke__hero-proof">
          <span className="release-smoke__status" data-status="pending">
            <i aria-hidden="true" />
            Awaiting first run
          </span>
          <span>0 shared briefs</span>
          <span>Independent results</span>
        </div>
      </PageHero>

      <section aria-labelledby="release-smoke-pending-title" className="release-smoke__pending">
        <div>
          <span>Pending evidence</span>
          <h2 id="release-smoke-pending-title">Nothing has been generated yet.</h2>
        </div>
        <div className="release-smoke__pending-copy">
          <p>
            The first release run will give Codex and Claude the same two briefs: one with guided
            answers and one in surprise-me mode.
          </p>
          <p>
            This page stays empty until the generated source has been installed, checked, built,
            opened in a browser, and published with its real conversation.
          </p>
          <a
            className="button button--quiet"
            href="https://github.com/Zhangdroid/drever/actions/workflows/release-smoke.yml"
            rel="noreferrer"
            target="_blank"
          >
            View workflow <ArrowUpRightIcon />
          </a>
        </div>
      </section>
    </main>
  );
}

function PublishedReleaseSmokePage({
  data,
  latest,
}: {
  data: ReleaseSmokeData;
  latest: ReleaseSmokeRun;
}) {
  const previewRef = useRef<HTMLElement>(null);
  const [selectedRunId, setSelectedRunId] = useState(latest.id);
  const selectedRun = data.runs.find((run) => run.id === selectedRunId) ?? latest;
  const scenarios = releaseSmokeScenarios(selectedRun);
  const [selectedScenarioId, setSelectedScenarioId] = useState(scenarios[0]?.id ?? "");
  const selectedScenario =
    scenarios.find((scenario) => scenario.id === selectedScenarioId) ?? scenarios[0];
  const archivedRuns = releaseSmokeHistory(data);
  const providerCount = new Set(selectedRun.cases.map((scenario) => scenario.provider.id)).size;

  if (selectedScenario === undefined)
    throw new Error("A release smoke run requires at least one scenario.");

  const selectRun = (run: ReleaseSmokeRun) => {
    const nextScenario = releaseSmokeScenarios(run)[0];
    setSelectedRunId(run.id);
    setSelectedScenarioId(nextScenario?.id ?? "");
    requestAnimationFrame(() => {
      previewRef.current?.scrollIntoView({
        behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth",
        block: "start",
      });
    });
  };

  return (
    <main className="release-smoke" data-header-tone="light" id="main" tabIndex={-1}>
      <PageHero
        description={description}
        eyebrow="Built in public"
        title="Watch the prompt become a real deck."
      >
        <div className="release-smoke__hero-proof">
          <RunStatus run={selectedRun} />
          <span>
            {scenarios.length} shared {scenarios.length === 1 ? "brief" : "briefs"}
          </span>
          <span>
            {providerCount} AI {providerCount === 1 ? "system" : "systems"}
          </span>
        </div>
      </PageHero>

      <section
        aria-labelledby="release-smoke-latest-title"
        className="release-smoke__run"
        ref={previewRef}
      >
        <header className="release-smoke__run-heading">
          <div>
            <span>
              {selectedRun.id === latest.id
                ? selectedRun.kind === "preview"
                  ? "Preview run"
                  : "Latest run"
                : "Archived run"}
            </span>
            <h2 id="release-smoke-latest-title">
              {selectedRun.kind === "preview"
                ? `drever@${selectedRun.release.version}`
                : selectedRun.release.version}
            </h2>
          </div>
          <div className="release-smoke__run-links">
            <RunStatus run={selectedRun} />
            <a href={selectedRun.runner.workflowUrl} rel="noreferrer" target="_blank">
              {selectedRun.kind === "preview" ? "Harness" : "Workflow"} <ArrowUpRightIcon />
            </a>
            <a href={selectedRun.release.url} rel="noreferrer" target="_blank">
              Release <ArrowUpRightIcon />
            </a>
          </div>
        </header>

        <RunMetadata run={selectedRun} />
        {selectedRun.kind === "preview" ? (
          <p className="release-smoke__preview-note">
            Owner-authorized seed proof from the real harness. Automated post-release runs appear
            here after the workflow completes.
          </p>
        ) : null}

        <nav aria-label="Release smoke scenarios" className="release-smoke__cases">
          {scenarios.map((scenario, index) => (
            <button
              aria-pressed={scenario.id === selectedScenario.id}
              key={scenario.id}
              onClick={() => setSelectedScenarioId(scenario.id)}
              type="button"
            >
              <span>0{index + 1}</span>
              <strong>{scenario.title}</strong>
              <small>
                {scenario.mode === "surprise-me" ? "Autonomous direction" : "Answered brief"}
              </small>
            </button>
          ))}
        </nav>

        <ScenarioComparison run={selectedRun} scenario={selectedScenario} />
      </section>

      <section aria-labelledby="release-smoke-archive-title" className="release-smoke__archive">
        <header>
          <span>History</span>
          <h2 id="release-smoke-archive-title">Every run stays with its release.</h2>
        </header>
        {archivedRuns.length === 0 ? (
          <div className="release-smoke__archive-empty">
            <p>
              The latest run lives here. Earlier immutable reports remain linked from their matching
              GitHub Releases.
            </p>
            <a
              className="button button--quiet"
              href="https://github.com/Zhangdroid/drever/releases"
              rel="noreferrer"
              target="_blank"
            >
              Browse release history <ArrowUpRightIcon />
            </a>
          </div>
        ) : (
          <div className="release-smoke__archive-list">
            {archivedRuns.map((run) => (
              <button
                aria-pressed={run.id === selectedRun.id}
                key={run.id}
                onClick={() => selectRun(run)}
                type="button"
              >
                <span>{formatDate(run.generatedAt)}</span>
                <strong>{run.release.version}</strong>
                <RunStatus run={run} />
              </button>
            ))}
          </div>
        )}
      </section>
    </main>
  );
}

function LoadingReleaseSmokePage() {
  return (
    <main
      aria-busy="true"
      className="release-smoke"
      data-header-tone="light"
      id="main"
      tabIndex={-1}
    >
      <PageHero
        description={description}
        eyebrow="Built in public"
        title="Watch the prompt become a real deck."
      >
        <div className="release-smoke__hero-proof">
          <span className="release-smoke__status" data-status="pending">
            <i aria-hidden="true" />
            Loading published runs
          </span>
          <span>Remote evidence</span>
          <span>No fixture decks</span>
        </div>
      </PageHero>

      <section aria-labelledby="release-smoke-loading-title" className="release-smoke__pending">
        <div>
          <span>Loading evidence</span>
          <h2 id="release-smoke-loading-title">Finding the latest verified run.</h2>
        </div>
        <div aria-live="polite" className="release-smoke__pending-copy" role="status">
          <p>
            The conversation, verification record, and interactive decks are loading from their
            isolated release-smoke origin.
          </p>
        </div>
      </section>
    </main>
  );
}

function FailedReleaseSmokePage({ retry }: { retry: () => void }) {
  return (
    <main className="release-smoke" data-header-tone="light" id="main" tabIndex={-1}>
      <PageHero
        description={description}
        eyebrow="Built in public"
        title="Watch the prompt become a real deck."
      >
        <div className="release-smoke__hero-proof">
          <span className="release-smoke__status" data-status="failed">
            <i aria-hidden="true" />
            Evidence unavailable
          </span>
          <span>Remote archive</span>
          <span>No fixture fallback</span>
        </div>
      </PageHero>

      <section aria-labelledby="release-smoke-error-title" className="release-smoke__pending">
        <div>
          <span>Could not load</span>
          <h2 id="release-smoke-error-title">The published archive is temporarily unavailable.</h2>
        </div>
        <div aria-live="polite" className="release-smoke__pending-copy" role="alert">
          <p>
            Drever keeps generated evidence on a separate static origin. The website could not reach
            it, so it will not substitute a showcase or fixture deck.
          </p>
          <button className="button button--primary" onClick={retry} type="button">
            Try again
          </button>
        </div>
      </section>
    </main>
  );
}

type ReleaseSmokeLoadState =
  | { status: "error" }
  | { status: "loaded"; data: ReleaseSmokeData }
  | { status: "loading" };

function ReleaseSmokePage() {
  const [attempt, setAttempt] = useState(0);
  const [state, setState] = useState<ReleaseSmokeLoadState>({ status: "loading" });

  useEffect(() => {
    const controller = new AbortController();
    setState({ status: "loading" });
    void loadReleaseSmokeData({ signal: controller.signal }).then(
      (data) => setState({ data, status: "loaded" }),
      () => {
        if (!controller.signal.aborted) setState({ status: "error" });
      },
    );
    return () => controller.abort();
  }, [attempt]);

  if (state.status === "loading") return <LoadingReleaseSmokePage />;
  if (state.status === "error") {
    return <FailedReleaseSmokePage retry={() => setAttempt((value) => value + 1)} />;
  }
  return state.data.latest === null ? (
    <EmptyReleaseSmokePage />
  ) : (
    <PublishedReleaseSmokePage data={state.data} latest={state.data.latest} />
  );
}
