/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ChangelogRouteImport } from "./routes/changelog";
import { Route as DemosRouteImport } from "./routes/demos";
import { Route as DocsRouteImport } from "./routes/docs";
import { Route as ReleaseSmokeRouteImport } from "./routes/release-smoke";
import { Route as ShowcaseRouteImport } from "./routes/showcase";
import { Route as ThemesRouteImport } from "./routes/themes";
import { Route as DocsIndexRouteImport } from "./routes/docs.index";
import { Route as DocsAiRouteImport } from "./routes/docs.ai";
import { Route as DocsAuthoringRouteImport } from "./routes/docs.authoring";
import { Route as DocsCommandsRouteImport } from "./routes/docs.commands";
import { Route as DocsConfigurationRouteImport } from "./routes/docs.configuration";
import { Route as DocsCreditsRouteImport } from "./routes/docs.credits";
import { Route as DocsDeliveryRouteImport } from "./routes/docs.delivery";
import { Route as DocsGettingStartedRouteImport } from "./routes/docs.getting-started";
import { Route as DocsMotionRouteImport } from "./routes/docs.motion";
import { Route as DocsPluginsRouteImport } from "./routes/docs.plugins";
import { Route as DocsPresentingRouteImport } from "./routes/docs.presenting";
import { Route as DocsReviewRouteImport } from "./routes/docs.review";
import { Route as DocsStudioRouteImport } from "./routes/docs.studio";
import { Route as DocsThemesRouteImport } from "./routes/docs.themes";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogRoute = ChangelogRouteImport.update({
  id: "/changelog",
  path: "/changelog",
  getParentRoute: () => rootRouteImport,
} as any);
const DemosRoute = DemosRouteImport.update({
  id: "/demos",
  path: "/demos",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsRoute = DocsRouteImport.update({
  id: "/docs",
  path: "/docs",
  getParentRoute: () => rootRouteImport,
} as any);
const ReleaseSmokeRoute = ReleaseSmokeRouteImport.update({
  id: "/release-smoke",
  path: "/release-smoke",
  getParentRoute: () => rootRouteImport,
} as any);
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: "/showcase",
  path: "/showcase",
  getParentRoute: () => rootRouteImport,
} as any);
const ThemesRoute = ThemesRouteImport.update({
  id: "/themes",
  path: "/themes",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DocsRoute,
} as any);
const DocsAiRoute = DocsAiRouteImport.update({
  id: "/ai",
  path: "/ai",
  getParentRoute: () => DocsRoute,
} as any);
const DocsAuthoringRoute = DocsAuthoringRouteImport.update({
  id: "/authoring",
  path: "/authoring",
  getParentRoute: () => DocsRoute,
} as any);
const DocsCommandsRoute = DocsCommandsRouteImport.update({
  id: "/commands",
  path: "/commands",
  getParentRoute: () => DocsRoute,
} as any);
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: "/configuration",
  path: "/configuration",
  getParentRoute: () => DocsRoute,
} as any);
const DocsCreditsRoute = DocsCreditsRouteImport.update({
  id: "/credits",
  path: "/credits",
  getParentRoute: () => DocsRoute,
} as any);
const DocsDeliveryRoute = DocsDeliveryRouteImport.update({
  id: "/delivery",
  path: "/delivery",
  getParentRoute: () => DocsRoute,
} as any);
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: "/getting-started",
  path: "/getting-started",
  getParentRoute: () => DocsRoute,
} as any);
const DocsMotionRoute = DocsMotionRouteImport.update({
  id: "/motion",
  path: "/motion",
  getParentRoute: () => DocsRoute,
} as any);
const DocsPluginsRoute = DocsPluginsRouteImport.update({
  id: "/plugins",
  path: "/plugins",
  getParentRoute: () => DocsRoute,
} as any);
const DocsPresentingRoute = DocsPresentingRouteImport.update({
  id: "/presenting",
  path: "/presenting",
  getParentRoute: () => DocsRoute,
} as any);
const DocsReviewRoute = DocsReviewRouteImport.update({
  id: "/review",
  path: "/review",
  getParentRoute: () => DocsRoute,
} as any);
const DocsStudioRoute = DocsStudioRouteImport.update({
  id: "/studio",
  path: "/studio",
  getParentRoute: () => DocsRoute,
} as any);
const DocsThemesRoute = DocsThemesRouteImport.update({
  id: "/themes",
  path: "/themes",
  getParentRoute: () => DocsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/changelog": typeof ChangelogRoute;
  "/demos": typeof DemosRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/release-smoke": typeof ReleaseSmokeRoute;
  "/showcase": typeof ShowcaseRoute;
  "/themes": typeof ThemesRoute;
  "/docs/ai": typeof DocsAiRoute;
  "/docs/authoring": typeof DocsAuthoringRoute;
  "/docs/commands": typeof DocsCommandsRoute;
  "/docs/configuration": typeof DocsConfigurationRoute;
  "/docs/credits": typeof DocsCreditsRoute;
  "/docs/delivery": typeof DocsDeliveryRoute;
  "/docs/getting-started": typeof DocsGettingStartedRoute;
  "/docs/motion": typeof DocsMotionRoute;
  "/docs/plugins": typeof DocsPluginsRoute;
  "/docs/presenting": typeof DocsPresentingRoute;
  "/docs/review": typeof DocsReviewRoute;
  "/docs/studio": typeof DocsStudioRoute;
  "/docs/themes": typeof DocsThemesRoute;
  "/docs/": typeof DocsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/changelog": typeof ChangelogRoute;
  "/demos": typeof DemosRoute;
  "/release-smoke": typeof ReleaseSmokeRoute;
  "/showcase": typeof ShowcaseRoute;
  "/themes": typeof ThemesRoute;
  "/docs/ai": typeof DocsAiRoute;
  "/docs/authoring": typeof DocsAuthoringRoute;
  "/docs/commands": typeof DocsCommandsRoute;
  "/docs/configuration": typeof DocsConfigurationRoute;
  "/docs/credits": typeof DocsCreditsRoute;
  "/docs/delivery": typeof DocsDeliveryRoute;
  "/docs/getting-started": typeof DocsGettingStartedRoute;
  "/docs/motion": typeof DocsMotionRoute;
  "/docs/plugins": typeof DocsPluginsRoute;
  "/docs/presenting": typeof DocsPresentingRoute;
  "/docs/review": typeof DocsReviewRoute;
  "/docs/studio": typeof DocsStudioRoute;
  "/docs/themes": typeof DocsThemesRoute;
  "/docs": typeof DocsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/changelog": typeof ChangelogRoute;
  "/demos": typeof DemosRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/release-smoke": typeof ReleaseSmokeRoute;
  "/showcase": typeof ShowcaseRoute;
  "/themes": typeof ThemesRoute;
  "/docs/ai": typeof DocsAiRoute;
  "/docs/authoring": typeof DocsAuthoringRoute;
  "/docs/commands": typeof DocsCommandsRoute;
  "/docs/configuration": typeof DocsConfigurationRoute;
  "/docs/credits": typeof DocsCreditsRoute;
  "/docs/delivery": typeof DocsDeliveryRoute;
  "/docs/getting-started": typeof DocsGettingStartedRoute;
  "/docs/motion": typeof DocsMotionRoute;
  "/docs/plugins": typeof DocsPluginsRoute;
  "/docs/presenting": typeof DocsPresentingRoute;
  "/docs/review": typeof DocsReviewRoute;
  "/docs/studio": typeof DocsStudioRoute;
  "/docs/themes": typeof DocsThemesRoute;
  "/docs/": typeof DocsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/changelog"
    | "/demos"
    | "/docs"
    | "/release-smoke"
    | "/showcase"
    | "/themes"
    | "/docs/ai"
    | "/docs/authoring"
    | "/docs/commands"
    | "/docs/configuration"
    | "/docs/credits"
    | "/docs/delivery"
    | "/docs/getting-started"
    | "/docs/motion"
    | "/docs/plugins"
    | "/docs/presenting"
    | "/docs/review"
    | "/docs/studio"
    | "/docs/themes"
    | "/docs/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/changelog"
    | "/demos"
    | "/release-smoke"
    | "/showcase"
    | "/themes"
    | "/docs/ai"
    | "/docs/authoring"
    | "/docs/commands"
    | "/docs/configuration"
    | "/docs/credits"
    | "/docs/delivery"
    | "/docs/getting-started"
    | "/docs/motion"
    | "/docs/plugins"
    | "/docs/presenting"
    | "/docs/review"
    | "/docs/studio"
    | "/docs/themes"
    | "/docs";
  id:
    | "__root__"
    | "/"
    | "/changelog"
    | "/demos"
    | "/docs"
    | "/release-smoke"
    | "/showcase"
    | "/themes"
    | "/docs/ai"
    | "/docs/authoring"
    | "/docs/commands"
    | "/docs/configuration"
    | "/docs/credits"
    | "/docs/delivery"
    | "/docs/getting-started"
    | "/docs/motion"
    | "/docs/plugins"
    | "/docs/presenting"
    | "/docs/review"
    | "/docs/studio"
    | "/docs/themes"
    | "/docs/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ChangelogRoute: typeof ChangelogRoute;
  DemosRoute: typeof DemosRoute;
  DocsRoute: typeof DocsRouteWithChildren;
  ReleaseSmokeRoute: typeof ReleaseSmokeRoute;
  ShowcaseRoute: typeof ShowcaseRoute;
  ThemesRoute: typeof ThemesRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog": {
      id: "/changelog";
      path: "/changelog";
      fullPath: "/changelog";
      preLoaderRoute: typeof ChangelogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demos": {
      id: "/demos";
      path: "/demos";
      fullPath: "/demos";
      preLoaderRoute: typeof DemosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs": {
      id: "/docs";
      path: "/docs";
      fullPath: "/docs";
      preLoaderRoute: typeof DocsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/release-smoke": {
      id: "/release-smoke";
      path: "/release-smoke";
      fullPath: "/release-smoke";
      preLoaderRoute: typeof ReleaseSmokeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/showcase": {
      id: "/showcase";
      path: "/showcase";
      fullPath: "/showcase";
      preLoaderRoute: typeof ShowcaseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/themes": {
      id: "/themes";
      path: "/themes";
      fullPath: "/themes";
      preLoaderRoute: typeof ThemesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/": {
      id: "/docs/";
      path: "/";
      fullPath: "/docs/";
      preLoaderRoute: typeof DocsIndexRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/ai": {
      id: "/docs/ai";
      path: "/ai";
      fullPath: "/docs/ai";
      preLoaderRoute: typeof DocsAiRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/authoring": {
      id: "/docs/authoring";
      path: "/authoring";
      fullPath: "/docs/authoring";
      preLoaderRoute: typeof DocsAuthoringRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/commands": {
      id: "/docs/commands";
      path: "/commands";
      fullPath: "/docs/commands";
      preLoaderRoute: typeof DocsCommandsRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/configuration": {
      id: "/docs/configuration";
      path: "/configuration";
      fullPath: "/docs/configuration";
      preLoaderRoute: typeof DocsConfigurationRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/credits": {
      id: "/docs/credits";
      path: "/credits";
      fullPath: "/docs/credits";
      preLoaderRoute: typeof DocsCreditsRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/delivery": {
      id: "/docs/delivery";
      path: "/delivery";
      fullPath: "/docs/delivery";
      preLoaderRoute: typeof DocsDeliveryRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/getting-started": {
      id: "/docs/getting-started";
      path: "/getting-started";
      fullPath: "/docs/getting-started";
      preLoaderRoute: typeof DocsGettingStartedRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/motion": {
      id: "/docs/motion";
      path: "/motion";
      fullPath: "/docs/motion";
      preLoaderRoute: typeof DocsMotionRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/plugins": {
      id: "/docs/plugins";
      path: "/plugins";
      fullPath: "/docs/plugins";
      preLoaderRoute: typeof DocsPluginsRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/presenting": {
      id: "/docs/presenting";
      path: "/presenting";
      fullPath: "/docs/presenting";
      preLoaderRoute: typeof DocsPresentingRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/review": {
      id: "/docs/review";
      path: "/review";
      fullPath: "/docs/review";
      preLoaderRoute: typeof DocsReviewRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/studio": {
      id: "/docs/studio";
      path: "/studio";
      fullPath: "/docs/studio";
      preLoaderRoute: typeof DocsStudioRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/themes": {
      id: "/docs/themes";
      path: "/themes";
      fullPath: "/docs/themes";
      preLoaderRoute: typeof DocsThemesRouteImport;
      parentRoute: typeof DocsRoute;
    };
  }
}

interface DocsRouteChildren {
  DocsAiRoute: typeof DocsAiRoute;
  DocsAuthoringRoute: typeof DocsAuthoringRoute;
  DocsCommandsRoute: typeof DocsCommandsRoute;
  DocsConfigurationRoute: typeof DocsConfigurationRoute;
  DocsCreditsRoute: typeof DocsCreditsRoute;
  DocsDeliveryRoute: typeof DocsDeliveryRoute;
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute;
  DocsMotionRoute: typeof DocsMotionRoute;
  DocsPluginsRoute: typeof DocsPluginsRoute;
  DocsPresentingRoute: typeof DocsPresentingRoute;
  DocsReviewRoute: typeof DocsReviewRoute;
  DocsStudioRoute: typeof DocsStudioRoute;
  DocsThemesRoute: typeof DocsThemesRoute;
  DocsIndexRoute: typeof DocsIndexRoute;
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAiRoute: DocsAiRoute,
  DocsAuthoringRoute: DocsAuthoringRoute,
  DocsCommandsRoute: DocsCommandsRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsCreditsRoute: DocsCreditsRoute,
  DocsDeliveryRoute: DocsDeliveryRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsMotionRoute: DocsMotionRoute,
  DocsPluginsRoute: DocsPluginsRoute,
  DocsPresentingRoute: DocsPresentingRoute,
  DocsReviewRoute: DocsReviewRoute,
  DocsStudioRoute: DocsStudioRoute,
  DocsThemesRoute: DocsThemesRoute,
  DocsIndexRoute: DocsIndexRoute,
};

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  DemosRoute: DemosRoute,
  DocsRoute: DocsRouteWithChildren,
  ReleaseSmokeRoute: ReleaseSmokeRoute,
  ShowcaseRoute: ShowcaseRoute,
  ThemesRoute: ThemesRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
