import { execFile } from "node:child_process";
import { mkdtemp, readFile, realpath, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { expect, test } from "@playwright/test";

const execute = promisify(execFile);
const workspaceRoot = join(import.meta.dirname, "..");
const projectRoot = join(workspaceRoot, "examples", "basic");
const cli = join(workspaceRoot, "packages", "cli", "dist", "bin.mjs");
const environment = { ...process.env };
delete environment.FORCE_COLOR;

const agentFiles = [
  "AGENTS.md",
  ".agents/skills/drever-author-deck/SKILL.md",
  ".agents/skills/drever-author-deck/agents/openai.yaml",
  ".agents/skills/drever-create-deck/SKILL.md",
  ".agents/skills/drever-create-deck/agents/openai.yaml",
  ".agents/skills/drever-review-deck/SKILL.md",
  ".agents/skills/drever-review-deck/agents/openai.yaml",
] as const;

type AuthoringContext = Readonly<{
  version: number;
  sourcePath: string;
  canvas: Readonly<{ height: number; width: number }>;
  deck: Readonly<{
    version: number;
    slides: readonly Readonly<{
      id: string;
      index: number;
      title?: string;
      stepStops: readonly number[];
      speakerNotes: readonly unknown[];
      source: readonly Readonly<{
        value: string;
        range: Readonly<{
          path: string;
          start: Readonly<{ offset: number }>;
          end: Readonly<{ offset: number }>;
        }>;
      }>[];
    }>[];
  }>;
  design: Readonly<{
    theme: Readonly<{
      id: string;
      version?: string;
      manifest: Readonly<{ title: string }>;
      motion?: Readonly<{
        guidance?: readonly string[];
        id: string;
        intents: readonly string[];
      }>;
    }>;
    layouts: readonly Readonly<{ name: string }>[];
  }>;
  plugins: readonly Readonly<{ id: string; origin: string; version?: string }>[];
  preflight: Readonly<{
    version: number;
    sourcePath: string;
    slideCount: number;
    summary: Readonly<{ errors: number; info: number; warnings: number }>;
    diagnostics: readonly unknown[];
  }>;
}>;

const runCli = (cwd: string, ...arguments_: string[]) =>
  execute(process.execPath, [cli, ...arguments_], {
    cwd,
    env: environment,
    timeout: 30_000,
  });

const readAgentFiles = async (root: string): Promise<readonly string[]> =>
  Promise.all(agentFiles.map((path) => readFile(join(root, path), "utf8")));

test("the built CLI installs an idempotent agent kit without loading project config", async () => {
  const root = await realpath(await mkdtemp(join(tmpdir(), "drever-agent-sync-e2e-")));
  const userInstructions = "# Project instructions\n\nKeep this user-owned guidance.\n";

  try {
    await Promise.all([
      writeFile(join(root, "AGENTS.md"), userInstructions),
      writeFile(join(root, "drever.config.ts"), "export default {"),
    ]);

    const first = await runCli(root, "agent", "sync");
    expect(first.stdout).toBe("Synced Drever agent kit: 6 created, 1 updated, 0 unchanged.\n");

    const firstContents = await readAgentFiles(root);
    const agents = firstContents[0];
    if (agents === undefined) {
      throw new Error("Agent sync did not create AGENTS.md.");
    }
    expect(agents.startsWith(userInstructions)).toBe(true);
    expect(agents.match(/<!-- drever-agent-kit:start -->/gu)).toHaveLength(1);
    expect(agents.match(/<!-- drever-agent-kit:end -->/gu)).toHaveLength(1);
    expect(agents).toContain("drever context --json");

    for (const [index, contents] of firstContents.entries()) {
      if (agentFiles[index]?.endsWith("SKILL.md")) {
        expect(contents).toContain("<!-- Generated by `drever agent sync`. -->");
      }
      if (agentFiles[index]?.endsWith("openai.yaml")) {
        expect(contents).toContain("# Generated by `drever agent sync`.");
      }
    }

    const second = await runCli(root, "agent", "sync");
    expect(second.stdout).toBe("Synced Drever agent kit: 0 created, 0 updated, 7 unchanged.\n");
    expect(await readAgentFiles(root)).toEqual(firstContents);
  } finally {
    await rm(root, { force: true, recursive: true });
  }
});

test("the built CLI exposes the canonical basic-deck authoring context", async () => {
  const sourcePath = join(projectRoot, "slides.mdx");
  const source = await readFile(sourcePath, "utf8");
  const { stdout } = await runCli(projectRoot, "context", "--json");
  const context = JSON.parse(stdout) as AuthoringContext;

  expect(context.version).toBe(1);
  expect(context.sourcePath).toBe(sourcePath);
  expect(context.canvas).toEqual({ width: 1_600, height: 900 });
  expect(context.deck.version).toBe(2);
  expect(
    context.deck.slides.map(({ id, index, speakerNotes, stepStops, title }) => ({
      id,
      index,
      speakerNoteCount: speakerNotes.length,
      stepStops,
      title,
    })),
  ).toEqual([
    {
      id: "slide-1",
      index: 0,
      speakerNoteCount: 0,
      stepStops: [],
      title: "Slides can be software.",
    },
    {
      id: "slide-2",
      index: 1,
      speakerNoteCount: 1,
      stepStops: [2, 5],
      title: "Motion should carry meaning.",
    },
    {
      id: "slide-3",
      index: 2,
      speakerNoteCount: 0,
      stepStops: [],
      title: "Static output and living interface",
    },
    {
      id: "slide-4",
      index: 3,
      speakerNoteCount: 1,
      stepStops: [],
      title: "Interfaces remember.",
    },
    {
      id: "slide-5",
      index: 4,
      speakerNoteCount: 0,
      stepStops: [],
      title: "Ship the story.",
    },
  ]);

  const authoredBody = source.slice(source.indexOf("<Cover"));
  const expectedSlideSources = authoredBody.split("\n\n---\n\n").map((value) => value.trim());
  expect(
    context.deck.slides.map(({ source: fragments }) => fragments.map(({ value }) => value)),
  ).toEqual(expectedSlideSources.map((value) => [value]));
  for (const slide of context.deck.slides) {
    for (const fragment of slide.source) {
      expect(fragment.range.path).toBe(sourcePath);
      expect(source.slice(fragment.range.start.offset, fragment.range.end.offset)).toBe(
        fragment.value,
      );
    }
  }

  expect(context.design.theme).toMatchObject({
    id: "@drever/theme-default",
    version: "0.0.0",
    manifest: { title: "Drever Default" },
    motion: {
      id: "default",
      intents: ["focus", "replace", "compare", "stagger", "continuity"],
      guidance: expect.arrayContaining([
        "Reuse a continuity name only when the same visual object persists across adjacent slides.",
      ]),
    },
  });
  expect(context.design.layouts.map(({ name }) => name)).toEqual(["Cover", "TwoColumn"]);
  expect(context.plugins.map(({ id, origin, version }) => ({ id, origin, version }))).toEqual([
    { id: "@drever/plugin-shiki", origin: "default", version: "0.0.0" },
    { id: "@drever/plugin-tailwindcss", origin: "default", version: "0.0.0" },
  ]);
  expect(context.preflight).toEqual({
    version: 1,
    sourcePath,
    slideCount: 5,
    summary: { errors: 0, warnings: 0, info: 0 },
    diagnostics: [],
  });
});
