import { createHash, randomUUID } from "node:crypto";
import { link, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { isAbsolute, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";
import {
  DREVER_BUILD_API_VERSION,
  type BuildCapability,
  type BuildModule,
  type BuildPluginContext,
} from "@drever/plugin";
import type {
  CompilePlan,
  Diagnostic,
  DiagnosticResult,
  PlannedBuildPlugin,
  PlannedPlugin,
} from "@drever/schema";
import type { Pluggable, Plugin as UnifiedPlugin, Preset, Processor, Transformer } from "unified";
import type { Plugin, PluginOption } from "vite";
import { buildDiagnostic, errorMessage } from "./adapter-diagnostic.ts";
import { EMPTY_CONFIG, snapshotJson } from "./json-snapshot.ts";

export type ModuleNamespace = Readonly<Record<string, unknown>>;

export type ImportModule = (specifier: string) => Promise<ModuleNamespace>;

export type CanonicalBuildModules = Readonly<{
  remark: readonly Pluggable[];
  rehype: readonly Pluggable[];
  recma: readonly Pluggable[];
  vite: readonly Plugin[];
}>;

export type LoadBuildModulesOptions = Readonly<{
  root?: string;
  cacheDir?: string;
  importModule?: ImportModule;
}>;

export type CanonicalRemarkModules = readonly Pluggable[];

type BuildExecutionDetails = Readonly<{
  capability: "recma" | "rehype" | "remark";
  entry: PlannedBuildPlugin;
}>;

type ImporterFailure = Error &
  Readonly<{
    code: string;
    hint: string;
  }>;

const RELATIVE_SPECIFIER = /^\.{1,2}(?:[\\/]|$)/u;
const DEFAULT_CACHE_DIRECTORY = ".drever/cache/build-modules";

const isErrorCode = (error: unknown, code: string): boolean =>
  typeof error === "object" && error !== null && "code" in error && error.code === code;

const isImporterFailure = (error: unknown): error is ImporterFailure =>
  error instanceof Error &&
  "code" in error &&
  typeof error.code === "string" &&
  error.code.startsWith("DREVER_") &&
  "hint" in error &&
  typeof error.hint === "string";

const importerFailure = (
  code: string,
  message: string,
  hint: string,
  cause?: unknown,
): ImporterFailure =>
  Object.assign(new Error(message, cause === undefined ? undefined : { cause }), { code, hint });

const assertCanonicalSpecifier = (specifier: string): void => {
  if (!RELATIVE_SPECIFIER.test(specifier)) {
    return;
  }
  throw importerFailure(
    "DREVER_BUILD_MODULE_SPECIFIER_RELATIVE",
    `Build module specifier "${specifier}" is still relative.`,
    "Set baseURL: import.meta.url on the extension so the compiler emits an absolute URL.",
  );
};

const isPathInside = (root: string, path: string): boolean => {
  const difference = relative(root, path);
  return (
    difference === "" ||
    (difference !== ".." && !difference.startsWith(`..${sep}`) && !isAbsolute(difference))
  );
};

const contentAddressedModule = async (
  cacheDirectory: string,
  specifier: string,
): Promise<string> => {
  const importSpecifier = isAbsolute(specifier) ? pathToFileURL(specifier).href : specifier;
  const source = [
    "// Generated by @drever/vite. This file is immutable and content-addressed.",
    `import * as buildModule from ${JSON.stringify(importSpecifier)};`,
    "export default buildModule;",
    "",
  ].join("\n");
  const digest = createHash("sha256").update(source).digest("hex");
  const path = resolve(cacheDirectory, `${digest}.mjs`);
  const temporaryPath = resolve(cacheDirectory, `.${digest}.${randomUUID()}.tmp`);

  await mkdir(cacheDirectory, { recursive: true });
  const assertCachedSource = async (): Promise<void> => {
    const cached = await readFile(path, "utf8");
    if (cached !== source) {
      throw importerFailure(
        "DREVER_BUILD_MODULE_CACHE_INVALID",
        `Build module cache entry "${path}" does not match its content address.`,
        "Remove the damaged .drever cache directory and run the build again.",
      );
    }
  };

  try {
    await assertCachedSource();
    return path;
  } catch (error) {
    if (!isErrorCode(error, "ENOENT")) throw error;
  }

  try {
    await writeFile(temporaryPath, source, { encoding: "utf8", flag: "wx" });
    try {
      await link(temporaryPath, path);
    } catch (error) {
      if (!isErrorCode(error, "EEXIST")) {
        throw error;
      }
      await assertCachedSource();
    }
  } finally {
    await rm(temporaryPath, { force: true });
  }
  return path;
};

const createProjectImporter = (options: LoadBuildModulesOptions): ImportModule => {
  const root = resolve(options.root ?? process.cwd());
  const cacheDirectory = resolve(root, options.cacheDir ?? DEFAULT_CACHE_DIRECTORY);

  return async (specifier) => {
    if (!isPathInside(root, cacheDirectory)) {
      throw importerFailure(
        "DREVER_BUILD_MODULE_CACHE_OUTSIDE_ROOT",
        `Build module cache directory "${cacheDirectory}" is outside project root "${root}".`,
        "Use a cacheDir inside the project root so bare ESM specifiers resolve from the project.",
      );
    }
    const path = await contentAddressedModule(cacheDirectory, specifier);
    const namespace = (await import(/* @vite-ignore */ pathToFileURL(path).href)) as Readonly<{
      default?: unknown;
    }>;
    if (typeof namespace.default !== "object" || namespace.default === null) {
      throw importerFailure(
        "DREVER_BUILD_MODULE_NAMESPACE_INVALID",
        `Build module proxy for "${specifier}" returned an invalid namespace.`,
        "Export the build descriptor from an ESM module.",
      );
    }
    return namespace.default as ModuleNamespace;
  };
};

const pluginIndex = (plugins: readonly PlannedPlugin[]): ReadonlyMap<string, PlannedPlugin> =>
  new Map(
    plugins.map((plugin) => [
      plugin.id,
      Object.freeze({
        ...plugin,
        ...(plugin.config === undefined ? {} : { config: snapshotJson(plugin.config) }),
      }),
    ]),
  );

const moduleExport = (
  namespace: ModuleNamespace,
  entry: PlannedBuildPlugin,
  capability: BuildCapability,
): DiagnosticResult<unknown> => {
  const exportName = entry.module.exportName ?? "default";
  if (!Object.hasOwn(namespace, exportName)) {
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          "DREVER_BUILD_MODULE_EXPORT_MISSING",
          `Build module "${entry.module.specifier}" does not export "${exportName}".`,
          "Export the declared name or update the module reference.",
          entry,
          { capability, exportName },
        ),
      ],
    };
  }
  return { ok: true, value: namespace[exportName], diagnostics: [] };
};

const validateDescriptor = <Capability extends BuildCapability>(
  value: unknown,
  capability: Capability,
  entry: PlannedBuildPlugin,
): DiagnosticResult<BuildModule<Capability, unknown>> => {
  if (typeof value !== "object" || value === null) {
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          "DREVER_BUILD_MODULE_INVALID",
          `Build module "${entry.module.specifier}" did not export a Drever build descriptor.`,
          "Wrap the contribution with defineRemarkPlugin, defineRehypePlugin, defineRecmaPlugin, or defineVitePlugin.",
          entry,
          { capability },
        ),
      ],
    };
  }

  const descriptor = value as Partial<BuildModule<Capability, unknown>>;
  if (descriptor.kind !== "drever-build-plugin" || typeof descriptor.create !== "function") {
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          "DREVER_BUILD_MODULE_INVALID",
          `Build module "${entry.module.specifier}" has an invalid Drever descriptor.`,
          "Export the result of a capability-specific @drever/plugin definition helper.",
          entry,
          { capability },
        ),
      ],
    };
  }
  if (descriptor.apiVersion !== DREVER_BUILD_API_VERSION) {
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          "DREVER_BUILD_API_VERSION",
          `Build module "${entry.module.specifier}" uses build API version ${String(descriptor.apiVersion)}.`,
          `Use build API version ${DREVER_BUILD_API_VERSION}.`,
          entry,
          {
            capability,
            extra: {
              actual: typeof descriptor.apiVersion === "number" ? descriptor.apiVersion : "invalid",
              expected: DREVER_BUILD_API_VERSION,
            },
          },
        ),
      ],
    };
  }
  if (descriptor.capability !== capability) {
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          "DREVER_BUILD_CAPABILITY_MISMATCH",
          `Build module "${entry.module.specifier}" declares capability "${String(descriptor.capability)}" instead of "${capability}".`,
          "Use the definition helper matching the build contribution field.",
          entry,
          {
            capability,
            extra: {
              actual: typeof descriptor.capability === "string" ? descriptor.capability : "invalid",
              expected: capability,
            },
          },
        ),
      ],
    };
  }
  return {
    ok: true,
    value: descriptor as BuildModule<Capability, unknown>,
    diagnostics: [],
  };
};

const createContext = <Capability extends BuildCapability>(
  capability: Capability,
  entry: PlannedBuildPlugin,
  plugin: PlannedPlugin,
  projectRoot: string,
): BuildPluginContext<Capability> =>
  Object.freeze({
    capability,
    phase: entry.phase,
    projectRoot,
    plugin: Object.freeze({
      id: plugin.id,
      ...(plugin.version === undefined ? {} : { version: plugin.version }),
    }),
    pluginConfig: plugin.config ?? EMPTY_CONFIG,
    hookOptions:
      entry.module.options === undefined ? undefined : snapshotJson(entry.module.options),
  });

const loadContribution = async <Capability extends BuildCapability>(
  capability: Capability,
  entry: PlannedBuildPlugin,
  plugins: ReadonlyMap<string, PlannedPlugin>,
  importer: ImportModule,
  projectRoot: string,
): Promise<DiagnosticResult<unknown>> => {
  const plugin = entry.owner.kind === "plugin" ? plugins.get(entry.owner.id) : undefined;
  if (plugin === undefined) {
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          "DREVER_BUILD_OWNER_MISSING",
          `Build contribution owner "${entry.owner.id}" is absent from the plan.`,
          "Regenerate the CompilePlan and do not edit it manually.",
          entry,
          { capability },
        ),
      ],
    };
  }

  let namespace: ModuleNamespace;
  try {
    assertCanonicalSpecifier(entry.module.specifier);
    namespace = await importer(entry.module.specifier);
  } catch (error) {
    const knownFailure = isImporterFailure(error);
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          knownFailure ? error.code : "DREVER_BUILD_MODULE_IMPORT_FAILED",
          knownFailure
            ? error.message
            : `Could not import build module "${entry.module.specifier}".`,
          knownFailure
            ? error.hint
            : "Check that the module exists, is ESM, and is installed by the extension package.",
          entry,
          { capability, cause: errorMessage(error) },
        ),
      ],
    };
  }

  const selected = moduleExport(namespace, entry, capability);
  if (!selected.ok) {
    return selected;
  }
  const descriptor = validateDescriptor(selected.value, capability, entry);
  if (!descriptor.ok) {
    return descriptor;
  }

  try {
    const value = await descriptor.value.create(
      createContext(capability, entry, plugin, projectRoot),
    );
    return { ok: true, value, diagnostics: [] };
  } catch (error) {
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          "DREVER_BUILD_MODULE_EXECUTION_FAILED",
          `Build module "${entry.module.specifier}" failed while creating its ${capability} contribution.`,
          "Check the plugin configuration and build module implementation.",
          entry,
          { capability, cause: errorMessage(error) },
        ),
      ],
    };
  }
};

export class DreverBuildPluginExecutionError extends Error {
  readonly code = "DREVER_BUILD_PLUGIN_EXECUTION_FAILED";
  readonly capability: BuildExecutionDetails["capability"];
  readonly phase: PlannedBuildPlugin["phase"];
  readonly plugin: string;
  readonly specifier: string;

  constructor(error: unknown, details: BuildExecutionDetails) {
    super(
      `Plugin "${details.entry.owner.id}" failed while executing its ${details.capability} contribution from "${details.entry.module.specifier}": ${errorMessage(error)}`,
      { cause: error },
    );
    this.name = "DreverBuildPluginExecutionError";
    this.capability = details.capability;
    this.phase = details.entry.phase;
    this.plugin = details.entry.owner.id;
    this.specifier = details.entry.module.specifier;
  }
}

const executionError = (error: unknown, details: BuildExecutionDetails): Error =>
  error instanceof DreverBuildPluginExecutionError
    ? error
    : new DreverBuildPluginExecutionError(error, details);

const wrapTransformer = (transformer: Transformer, details: BuildExecutionDetails): Transformer => {
  if (transformer.length >= 3) {
    return function wrappedCallbackTransformer(tree, file, callback) {
      try {
        return (transformer as TransformerWithCallback)(
          tree,
          file,
          (error, outputTree, outputFile) =>
            callback(
              error === undefined || error === null ? undefined : executionError(error, details),
              outputTree,
              outputFile,
            ),
        );
      } catch (error) {
        callback(executionError(error, details));
      }
    };
  }

  return function wrappedTransformer(tree, file) {
    try {
      const result = (transformer as TransformerWithoutCallback)(tree, file);
      if (result instanceof Error) {
        return executionError(result, details);
      }
      return isPromiseLike(result)
        ? Promise.resolve(result).catch((error: unknown) => {
            throw executionError(error, details);
          })
        : result;
    } catch (error) {
      throw executionError(error, details);
    }
  };
};

type TransformerWithCallback = (
  tree: Parameters<Transformer>[0],
  file: Parameters<Transformer>[1],
  callback: Parameters<Transformer>[2],
) => ReturnType<Transformer>;

type TransformerWithoutCallback = (
  tree: Parameters<Transformer>[0],
  file: Parameters<Transformer>[1],
) => ReturnType<Transformer>;

type RuntimeAttacher = (this: Processor, ...parameters: unknown[]) => unknown;

const isPromiseLike = (value: unknown): value is PromiseLike<unknown> =>
  (typeof value === "object" || typeof value === "function") &&
  value !== null &&
  "then" in value &&
  typeof value.then === "function";

const wrapAttacher = (
  attacher: RuntimeAttacher,
  parameters: readonly unknown[],
  details: BuildExecutionDetails,
): UnifiedPlugin => {
  const uniqueDreverAttacher = function (this: Processor) {
    try {
      const transformer = attacher.apply(this, [...parameters]);
      return typeof transformer === "function"
        ? wrapTransformer(transformer as Transformer, details)
        : transformer;
    } catch (error) {
      throw executionError(error, details);
    }
  };
  return uniqueDreverAttacher as UnifiedPlugin;
};

const normalizePluggable = (
  value: unknown,
  details: BuildExecutionDetails,
): Pluggable | undefined => {
  if (typeof value === "function") {
    return wrapAttacher(value as RuntimeAttacher, [], details);
  }
  if (Array.isArray(value)) {
    const [attacher, ...parameters] = value as unknown[];
    return typeof attacher === "function"
      ? wrapAttacher(attacher as RuntimeAttacher, parameters, details)
      : undefined;
  }
  if (typeof value !== "object" || value === null) {
    return;
  }

  const preset = value as Preset;
  if (preset.plugins !== undefined && !Array.isArray(preset.plugins)) {
    return;
  }
  const plugins: Pluggable[] = [];
  for (const child of preset.plugins ?? []) {
    const normalized = normalizePluggable(child, details);
    if (!normalized) {
      return;
    }
    plugins.push(normalized);
  }
  return {
    ...(preset.settings === undefined ? {} : { settings: preset.settings }),
    ...(preset.plugins === undefined ? {} : { plugins }),
  };
};

const loadUnified = async (
  capability: "recma" | "rehype" | "remark",
  entries: readonly PlannedBuildPlugin[],
  plugins: ReadonlyMap<string, PlannedPlugin>,
  importer: ImportModule,
  projectRoot: string,
): Promise<DiagnosticResult<readonly Pluggable[]>> => {
  const values: Pluggable[] = [];
  for (const entry of entries) {
    const result = await loadContribution(capability, entry, plugins, importer, projectRoot);
    if (!result.ok) {
      return result;
    }
    const normalized = normalizePluggable(result.value, { capability, entry });
    if (!normalized) {
      return {
        ok: false,
        diagnostics: [
          buildDiagnostic(
            "DREVER_BUILD_MODULE_RESULT_INVALID",
            `Build module "${entry.module.specifier}" returned an invalid ${capability} contribution.`,
            "Return a unified plugin, plugin tuple, or recursively valid preset.",
            entry,
            { capability },
          ),
        ],
      };
    }
    values.push(normalized);
  }
  return { ok: true, value: Object.freeze(values), diagnostics: [] };
};

const flattenVitePlugins = async (option: PluginOption): Promise<unknown[]> => {
  const resolved = await option;
  if (!resolved) {
    return [];
  }
  if (Array.isArray(resolved)) {
    const plugins: unknown[] = [];
    for (const child of resolved) {
      plugins.push(...(await flattenVitePlugins(child)));
    }
    return plugins;
  }
  return [resolved];
};

const cloneWithVitePhase = (plugin: Plugin, phase: "post" | "pre"): Plugin => {
  const descriptors: PropertyDescriptorMap = Object.getOwnPropertyDescriptors(plugin);
  const enforce = descriptors.enforce;
  descriptors.enforce = {
    configurable: enforce?.configurable ?? true,
    enumerable: enforce?.enumerable ?? true,
    value: phase,
    writable: enforce && "writable" in enforce ? (enforce.writable ?? true) : true,
  };
  return Object.create(Object.getPrototypeOf(plugin), descriptors) as Plugin;
};

const applyVitePhase = (
  plugin: Plugin,
  name: string,
  entry: PlannedBuildPlugin,
): DiagnosticResult<Plugin> => {
  const expected = entry.phase === "normal" ? undefined : entry.phase;
  let actual: Plugin["enforce"];
  try {
    actual = plugin.enforce;
  } catch (error) {
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          "DREVER_BUILD_MODULE_RESULT_INVALID",
          `Vite plugin "${name}" has an unreadable enforce phase.`,
          "Return a plain Vite plugin object and declare build.enforce on the Drever plugin.",
          entry,
          { capability: "vite", cause: errorMessage(error) },
        ),
      ],
    };
  }
  if (actual !== undefined && actual !== expected) {
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          "DREVER_VITE_PLUGIN_PHASE_CONFLICT",
          `Vite plugin "${name}" declares enforce "${actual}" but Drever planned phase "${entry.phase}".`,
          "Remove native enforce from the returned Vite plugin and declare build.enforce on the Drever plugin.",
          entry,
          {
            capability: "vite",
            extra: {
              actual,
              expected: expected ?? "normal",
              vitePlugin: name,
            },
          },
        ),
      ],
    };
  }
  try {
    return {
      ok: true,
      value: expected === undefined ? plugin : cloneWithVitePhase(plugin, expected),
      diagnostics: [],
    };
  } catch (error) {
    return {
      ok: false,
      diagnostics: [
        buildDiagnostic(
          "DREVER_BUILD_MODULE_RESULT_INVALID",
          `Vite plugin "${name}" could not accept its planned phase.`,
          "Return a plain Vite plugin object without proxy traps.",
          entry,
          { capability: "vite", cause: errorMessage(error) },
        ),
      ],
    };
  }
};

const loadVite = async (
  entries: readonly PlannedBuildPlugin[],
  plugins: ReadonlyMap<string, PlannedPlugin>,
  importer: ImportModule,
  projectRoot: string,
): Promise<DiagnosticResult<readonly Plugin[]>> => {
  const names = new Map<string, PlannedBuildPlugin>();
  const values: Plugin[] = [];
  for (const entry of entries) {
    const result = await loadContribution("vite", entry, plugins, importer, projectRoot);
    if (!result.ok) {
      return result;
    }
    let loaded: unknown[];
    try {
      loaded = await flattenVitePlugins(result.value as PluginOption);
    } catch (error) {
      return {
        ok: false,
        diagnostics: [
          buildDiagnostic(
            "DREVER_BUILD_MODULE_RESULT_INVALID",
            `Build module "${entry.module.specifier}" returned an invalid Vite contribution.`,
            "Return a Vite plugin or nested PluginOption array.",
            entry,
            { capability: "vite", cause: errorMessage(error) },
          ),
        ],
      };
    }
    for (const candidate of loaded) {
      if (typeof candidate !== "object" || candidate === null) {
        return {
          ok: false,
          diagnostics: [
            buildDiagnostic(
              "DREVER_BUILD_MODULE_RESULT_INVALID",
              `Build module "${entry.module.specifier}" returned an invalid Vite plugin.`,
              "Return Vite plugin objects with stable names.",
              entry,
              { capability: "vite" },
            ),
          ],
        };
      }
      const plugin = candidate as Plugin;
      let name: unknown;
      try {
        name = plugin.name;
      } catch (error) {
        return {
          ok: false,
          diagnostics: [
            buildDiagnostic(
              "DREVER_VITE_PLUGIN_NAME_INVALID",
              `Build module "${entry.module.specifier}" returned a Vite plugin with an unreadable name.`,
              "Return a Vite plugin with a non-empty stable name.",
              entry,
              { capability: "vite", cause: errorMessage(error) },
            ),
          ],
        };
      }
      if (typeof name !== "string" || name.trim().length === 0) {
        return {
          ok: false,
          diagnostics: [
            buildDiagnostic(
              "DREVER_VITE_PLUGIN_NAME_INVALID",
              `Build module "${entry.module.specifier}" returned a Vite plugin with an empty name.`,
              "Return a Vite plugin with a non-empty stable name.",
              entry,
              { capability: "vite" },
            ),
          ],
        };
      }
      const previous = names.get(name);
      if (previous) {
        return {
          ok: false,
          diagnostics: [
            buildDiagnostic(
              "DREVER_VITE_PLUGIN_NAME_DUPLICATE",
              `Vite plugin name "${name}" is contributed more than once.`,
              "Give every Vite plugin returned by Drever extensions a globally unique name.",
              entry,
              {
                capability: "vite",
                extra: {
                  firstOwner: `${previous.owner.kind}:${previous.owner.id}`,
                  vitePlugin: name,
                },
              },
            ),
          ],
        };
      }
      const phased = applyVitePhase(plugin, name, entry);
      if (!phased.ok) {
        return phased;
      }
      names.set(name, entry);
      values.push(phased.value);
    }
  }
  return { ok: true, value: Object.freeze(values), diagnostics: [] };
};

export const loadBuildModules = async (
  plan: CompilePlan,
  options: LoadBuildModulesOptions = {},
): Promise<DiagnosticResult<CanonicalBuildModules>> => {
  const plugins = pluginIndex(plan.plugins);
  const projectRoot = resolve(options.root ?? process.cwd());
  const importer = options.importModule ?? createProjectImporter(options);
  const remark = await loadUnified("remark", plan.build.remark, plugins, importer, projectRoot);
  if (!remark.ok) {
    return remark;
  }
  const rehype = await loadUnified("rehype", plan.build.rehype, plugins, importer, projectRoot);
  if (!rehype.ok) {
    return rehype;
  }
  const recma = await loadUnified("recma", plan.build.recma, plugins, importer, projectRoot);
  if (!recma.ok) {
    return recma;
  }
  const vite = await loadVite(plan.build.vite, plugins, importer, projectRoot);
  if (!vite.ok) {
    return vite;
  }

  return {
    ok: true,
    value: Object.freeze({
      remark: remark.value,
      rehype: rehype.value,
      recma: recma.value,
      vite: vite.value,
    }),
    diagnostics: [] as readonly Diagnostic[],
  };
};

/** Loads only the remark contributions needed to derive the canonical DeckManifest. */
export const loadRemarkModules = async (
  plan: CompilePlan,
  options: LoadBuildModulesOptions = {},
): Promise<DiagnosticResult<CanonicalRemarkModules>> => {
  const plugins = pluginIndex(plan.plugins);
  const projectRoot = resolve(options.root ?? process.cwd());
  const importer = options.importModule ?? createProjectImporter(options);
  return loadUnified("remark", plan.build.remark, plugins, importer, projectRoot);
};
