// Generated from tokens.json. Run `vp run -F @drever/brand generate` to update.

export const brandTokens = {
  color: {
    ink: "#172033",
    paper: "#F8F8F4",
    white: "#FFFFFF",
    coral: "#FF704D",
    coralSoft: "#FFE4DC",
    indigo: "#4B56E8",
    indigoSoft: "#E5E7FF",
    graphite: "#667085",
    line: "#D9DDE7",
    night: "#0D1019",
    nightSurface: "#181C2B",
    nightLine: "#353A4F",
    nightText: "#F8F8F4",
    nightMuted: "#AEB5C6",
  },
  font: {
    family: {
      sans: '"Instrument Sans", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
      mono: '"SFMono-Regular", "Cascadia Code", "Roboto Mono", ui-monospace, monospace',
    },
    weight: {
      regular: "400",
      medium: "520",
      semibold: "650",
      bold: "700",
    },
    width: {
      display: "82",
      compact: "88",
      text: "100",
    },
    lineHeight: {
      display: "0.92",
      heading: "1.04",
      body: "1.5",
    },
    tracking: {
      display: "-0.055",
      heading: "-0.035",
      body: "-0.012",
      label: "0.1",
    },
  },
  space: {
    zero: "0px",
    one: "0.25rem",
    two: "0.5rem",
    three: "0.75rem",
    four: "1rem",
    six: "1.5rem",
    eight: "2rem",
    twelve: "3rem",
    sixteen: "4rem",
    twentyFour: "6rem",
  },
  radius: {
    zero: "0px",
    small: "0.5rem",
    medium: "0.875rem",
    large: "1.25rem",
    xlarge: "2rem",
    full: "999px",
  },
  stroke: {
    hairline: "1px",
    strong: "2px",
  },
  motion: {
    duration: {
      instant: "120ms",
      quick: "180ms",
      standard: "320ms",
      expressive: "520ms",
    },
    easing: {
      standard: "cubic-bezier(0.22, 1, 0.36, 1)",
      emphasized: "cubic-bezier(0.16, 1, 0.3, 1)",
      exit: "cubic-bezier(0.4, 0, 1, 1)",
    },
  },
} as const;

export const brandTokenValues = {
  "color.ink": brandTokens.color.ink,
  "color.paper": brandTokens.color.paper,
  "color.white": brandTokens.color.white,
  "color.coral": brandTokens.color.coral,
  "color.coralSoft": brandTokens.color.coralSoft,
  "color.indigo": brandTokens.color.indigo,
  "color.indigoSoft": brandTokens.color.indigoSoft,
  "color.graphite": brandTokens.color.graphite,
  "color.line": brandTokens.color.line,
  "color.night": brandTokens.color.night,
  "color.nightSurface": brandTokens.color.nightSurface,
  "color.nightLine": brandTokens.color.nightLine,
  "color.nightText": brandTokens.color.nightText,
  "color.nightMuted": brandTokens.color.nightMuted,
  "font.family.sans": brandTokens.font.family.sans,
  "font.family.mono": brandTokens.font.family.mono,
  "font.weight.regular": brandTokens.font.weight.regular,
  "font.weight.medium": brandTokens.font.weight.medium,
  "font.weight.semibold": brandTokens.font.weight.semibold,
  "font.weight.bold": brandTokens.font.weight.bold,
  "font.width.display": brandTokens.font.width.display,
  "font.width.compact": brandTokens.font.width.compact,
  "font.width.text": brandTokens.font.width.text,
  "font.lineHeight.display": brandTokens.font.lineHeight.display,
  "font.lineHeight.heading": brandTokens.font.lineHeight.heading,
  "font.lineHeight.body": brandTokens.font.lineHeight.body,
  "font.tracking.display": brandTokens.font.tracking.display,
  "font.tracking.heading": brandTokens.font.tracking.heading,
  "font.tracking.body": brandTokens.font.tracking.body,
  "font.tracking.label": brandTokens.font.tracking.label,
  "space.zero": brandTokens.space.zero,
  "space.one": brandTokens.space.one,
  "space.two": brandTokens.space.two,
  "space.three": brandTokens.space.three,
  "space.four": brandTokens.space.four,
  "space.six": brandTokens.space.six,
  "space.eight": brandTokens.space.eight,
  "space.twelve": brandTokens.space.twelve,
  "space.sixteen": brandTokens.space.sixteen,
  "space.twentyFour": brandTokens.space.twentyFour,
  "radius.zero": brandTokens.radius.zero,
  "radius.small": brandTokens.radius.small,
  "radius.medium": brandTokens.radius.medium,
  "radius.large": brandTokens.radius.large,
  "radius.xlarge": brandTokens.radius.xlarge,
  "radius.full": brandTokens.radius.full,
  "stroke.hairline": brandTokens.stroke.hairline,
  "stroke.strong": brandTokens.stroke.strong,
  "motion.duration.instant": brandTokens.motion.duration.instant,
  "motion.duration.quick": brandTokens.motion.duration.quick,
  "motion.duration.standard": brandTokens.motion.duration.standard,
  "motion.duration.expressive": brandTokens.motion.duration.expressive,
  "motion.easing.standard": brandTokens.motion.easing.standard,
  "motion.easing.emphasized": brandTokens.motion.easing.emphasized,
  "motion.easing.exit": brandTokens.motion.easing.exit,
} as const;

export type BrandTokenPath = keyof typeof brandTokenValues;
export type BrandTokens = typeof brandTokens;
