// Generated from tokens.json. Run `vp run -F @drever/brand generate` to update.

export const brandTokens = {
  color: {
    ink: "#19172B",
    paper: "#F6F3E9",
    white: "#FFFFFF",
    signal: "#C7F03A",
    signalSoft: "#ECF8C6",
    continuity: "#5B45D8",
    continuitySoft: "#E9E4FF",
    graphite: "#686474",
    line: "#D9D4E1",
    night: "#111018",
    nightSurface: "#1D1A2A",
    nightLine: "#3A3549",
    nightText: "#F6F3E9",
    nightMuted: "#B9B3C7",
  },
  font: {
    family: {
      display:
        '"Bricolage Grotesque", "Instrument Sans", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
      sans: '"Instrument Sans", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
      mono: '"SFMono-Regular", "Cascadia Code", "Roboto Mono", ui-monospace, monospace',
    },
    weight: {
      regular: "400",
      medium: "520",
      semibold: "650",
      bold: "700",
    },
    width: {
      display: "100",
      compact: "100",
      text: "100",
    },
    lineHeight: {
      display: "0.92",
      heading: "1.04",
      body: "1.5",
    },
    tracking: {
      display: "-0.03",
      heading: "-0.02",
      body: "-0.012",
      label: "0.1",
    },
  },
  geometry: {
    shift: "0.75rem",
    signalRail: "0.125rem",
    signalBand: "0.75rem",
  },
  space: {
    zero: "0px",
    one: "0.25rem",
    two: "0.5rem",
    three: "0.75rem",
    four: "1rem",
    six: "1.5rem",
    eight: "2rem",
    twelve: "3rem",
    sixteen: "4rem",
    twentyFour: "6rem",
  },
  radius: {
    zero: "0px",
    small: "0.5rem",
    medium: "0.875rem",
    large: "1.25rem",
    xlarge: "2rem",
    full: "999px",
  },
  stroke: {
    hairline: "1px",
    strong: "2px",
  },
  material: {
    irisGlass: {
      blur: "1.125rem",
      saturation: "1.35",
      surfaceOpacity: "0.72",
      overlayOpacity: "0.88",
    },
  },
  motion: {
    duration: {
      instant: "120ms",
      quick: "180ms",
      standard: "320ms",
      expressive: "520ms",
    },
    easing: {
      standard: "cubic-bezier(0.22, 1, 0.36, 1)",
      emphasized: "cubic-bezier(0.16, 1, 0.3, 1)",
      exit: "cubic-bezier(0.4, 0, 1, 1)",
    },
  },
} as const;

export const brandTokenValues = {
  "color.ink": brandTokens.color.ink,
  "color.paper": brandTokens.color.paper,
  "color.white": brandTokens.color.white,
  "color.signal": brandTokens.color.signal,
  "color.signalSoft": brandTokens.color.signalSoft,
  "color.continuity": brandTokens.color.continuity,
  "color.continuitySoft": brandTokens.color.continuitySoft,
  "color.graphite": brandTokens.color.graphite,
  "color.line": brandTokens.color.line,
  "color.night": brandTokens.color.night,
  "color.nightSurface": brandTokens.color.nightSurface,
  "color.nightLine": brandTokens.color.nightLine,
  "color.nightText": brandTokens.color.nightText,
  "color.nightMuted": brandTokens.color.nightMuted,
  "font.family.display": brandTokens.font.family.display,
  "font.family.sans": brandTokens.font.family.sans,
  "font.family.mono": brandTokens.font.family.mono,
  "font.weight.regular": brandTokens.font.weight.regular,
  "font.weight.medium": brandTokens.font.weight.medium,
  "font.weight.semibold": brandTokens.font.weight.semibold,
  "font.weight.bold": brandTokens.font.weight.bold,
  "font.width.display": brandTokens.font.width.display,
  "font.width.compact": brandTokens.font.width.compact,
  "font.width.text": brandTokens.font.width.text,
  "font.lineHeight.display": brandTokens.font.lineHeight.display,
  "font.lineHeight.heading": brandTokens.font.lineHeight.heading,
  "font.lineHeight.body": brandTokens.font.lineHeight.body,
  "font.tracking.display": brandTokens.font.tracking.display,
  "font.tracking.heading": brandTokens.font.tracking.heading,
  "font.tracking.body": brandTokens.font.tracking.body,
  "font.tracking.label": brandTokens.font.tracking.label,
  "geometry.shift": brandTokens.geometry.shift,
  "geometry.signalRail": brandTokens.geometry.signalRail,
  "geometry.signalBand": brandTokens.geometry.signalBand,
  "space.zero": brandTokens.space.zero,
  "space.one": brandTokens.space.one,
  "space.two": brandTokens.space.two,
  "space.three": brandTokens.space.three,
  "space.four": brandTokens.space.four,
  "space.six": brandTokens.space.six,
  "space.eight": brandTokens.space.eight,
  "space.twelve": brandTokens.space.twelve,
  "space.sixteen": brandTokens.space.sixteen,
  "space.twentyFour": brandTokens.space.twentyFour,
  "radius.zero": brandTokens.radius.zero,
  "radius.small": brandTokens.radius.small,
  "radius.medium": brandTokens.radius.medium,
  "radius.large": brandTokens.radius.large,
  "radius.xlarge": brandTokens.radius.xlarge,
  "radius.full": brandTokens.radius.full,
  "stroke.hairline": brandTokens.stroke.hairline,
  "stroke.strong": brandTokens.stroke.strong,
  "material.irisGlass.blur": brandTokens.material.irisGlass.blur,
  "material.irisGlass.saturation": brandTokens.material.irisGlass.saturation,
  "material.irisGlass.surfaceOpacity": brandTokens.material.irisGlass.surfaceOpacity,
  "material.irisGlass.overlayOpacity": brandTokens.material.irisGlass.overlayOpacity,
  "motion.duration.instant": brandTokens.motion.duration.instant,
  "motion.duration.quick": brandTokens.motion.duration.quick,
  "motion.duration.standard": brandTokens.motion.duration.standard,
  "motion.duration.expressive": brandTokens.motion.duration.expressive,
  "motion.easing.standard": brandTokens.motion.easing.standard,
  "motion.easing.emphasized": brandTokens.motion.easing.emphasized,
  "motion.easing.exit": brandTokens.motion.easing.exit,
} as const;

export type BrandTokenPath = keyof typeof brandTokenValues;
export type BrandTokens = typeof brandTokens;
