import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, describe, expect, it } from "vite-plus/test";
import { syncAgentKit } from "./agent-sync.ts";
import { DreverCliError } from "./errors.ts";
import { decodeStudioAgentState } from "./studio-plugin.ts";

const AGENTS_START = "<!-- drever-agent-kit:start -->";
const AGENTS_END = "<!-- drever-agent-kit:end -->";
const SKILL_MARKER = "<!-- Generated by `drever agent sync`. -->";
const YAML_MARKER = "# Generated by `drever agent sync`.";
const SKILLS = [
  "drever-author-deck",
  "drever-create-deck",
  "drever-create-design",
  "drever-review-deck",
  "drever-deliver-deck",
] as const;
const SKILL_RESOURCES: Partial<Record<(typeof SKILLS)[number], readonly string[]>> = {
  "drever-create-design": ["references/visual-decision-pass.md"],
};
const CODEX_TARGETS = [
  "AGENTS.md",
  ...SKILLS.flatMap((skill) => [
    `.agents/skills/${skill}/SKILL.md`,
    ...(SKILL_RESOURCES[skill] ?? []).map((path) => `.agents/skills/${skill}/${path}`),
    `.agents/skills/${skill}/agents/openai.yaml`,
  ]),
] as const;
const CLAUDE_TARGETS = [
  "CLAUDE.md",
  ...SKILLS.flatMap((skill) => [
    `.claude/skills/${skill}/SKILL.md`,
    ...(SKILL_RESOURCES[skill] ?? []).map((path) => `.claude/skills/${skill}/${path}`),
  ]),
] as const;

const directories: string[] = [];

const temporaryDirectory = async (name: string): Promise<string> => {
  const directory = await mkdtemp(join(tmpdir(), name));
  directories.push(directory);
  return directory;
};

const write = async (root: string, path: string, contents: string): Promise<void> => {
  const destination = join(root, path);
  await mkdir(dirname(destination), { recursive: true });
  await writeFile(destination, contents, "utf8");
};

const read = (root: string, path: string): Promise<string> => readFile(join(root, path), "utf8");

const createTemplateKit = async (version: string): Promise<string> => {
  const root = await temporaryDirectory("drever-agent-kit-");
  await write(
    root,
    "AGENTS.md",
    `${AGENTS_START}\n## Drever agent kit ${version}\n\nUse the Drever skills.\n${AGENTS_END}\n`,
  );
  await Promise.all(
    SKILLS.flatMap((skill) => [
      write(
        root,
        `skills/${skill}/SKILL.md`,
        `${SKILL_MARKER}\n---\nname: ${skill}\n---\n\n# ${skill} ${version}\n`,
      ),
      write(
        root,
        `skills/${skill}/agents/openai.yaml`,
        `${YAML_MARKER}\ninterface:\n  display_name: ${skill} ${version}\n`,
      ),
      ...(SKILL_RESOURCES[skill] ?? []).map((path) =>
        write(
          root,
          `skills/${skill}/${path}`,
          `${SKILL_MARKER}\n\n# ${skill} reference ${version}\n`,
        ),
      ),
    ]),
  );
  return root;
};

afterEach(async () => {
  await Promise.all(
    directories.splice(0).map((path) => rm(path, { force: true, recursive: true })),
  );
});

describe("agent kit sync", () => {
  it("resolves the bundled kit from the source module", async () => {
    const root = await temporaryDirectory("drever-agent-project-");

    const result = await syncAgentKit({ root });

    expect(result.files).toEqual(CODEX_TARGETS.map((path) => ({ path, status: "created" })));
    await expect(read(root, "AGENTS.md")).resolves.toContain("## Drever presentation authoring");
    await expect(read(root, ".agents/skills/drever-review-deck/SKILL.md")).resolves.toContain(
      "name: drever-review-deck",
    );
    await expect(read(root, ".agents/skills/drever-deliver-deck/SKILL.md")).resolves.toContain(
      "name: drever-deliver-deck",
    );
  });

  it("installs the blocking rendered-readability contract across the authoring workflow", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const installed = new Map<string, string>();
    for (const skill of [
      "drever-create-design",
      "drever-author-deck",
      "drever-review-deck",
    ] as const) {
      const contents = await read(root, `.agents/skills/${skill}/SKILL.md`);
      installed.set(skill, contents);
      expect(contents).toMatch(/Every visible authored string is a reading promise/iu);
      expect(contents).toMatch(
        /not\s+immediately legible at\s+presentation distance[^.]*blocking P0 defect/iu,
      );
      expect(contents).toMatch(/ancestor's\s+`color`\s+is not\s+proof/iu);
      expect(contents).toMatch(
        /fully contained within the shape or surface that visually owns it/iu,
      );
      expect(contents).toMatch(/usable inner silhouette[^.]*rectangular bounding box/iu);
    }

    const createDeck = await read(root, ".agents/skills/drever-create-deck/SKILL.md");
    expect(createDeck).not.toMatch(/drever check --rendered/iu);
    expect(installed.get("drever-review-deck")).toContain(
      "drever check --rendered --evidence .drever/review --json",
    );
    expect(createDeck).toMatch(/`drever-review-deck`[^.]*single owner/iu);
    expect(installed.get("drever-create-design")).toMatch(
      /every affected slide at Step 0 and every affected exact Step state/iu,
    );
    expect(installed.get("drever-review-deck")).toMatch(
      /every slide at Step 0 and every exact sparse Step state/iu,
    );
    expect(installed.get("drever-author-deck")).toMatch(
      /every affected\s+exact slide and Step route/iu,
    );
    expect(installed.get("drever-author-deck")).toMatch(
      /Expand the gate to the whole deck[^.]*shared theme/iu,
    );
  });

  it("installs the unified briefing and topic-specific signature contract", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const createDeck = await read(root, ".agents/skills/drever-create-deck/SKILL.md");
    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    expect(createDeck).toContain("<!-- drever-briefing-contract:v4 -->");
    expect(createDeck).toMatch(/topic is missing[^.]*one short open question/iu);
    expect(createDeck).toMatch(/one to\s+three decisions per round/iu);
    expect(createDeck).toMatch(/two to four topic-specific choices/iu);
    expect(createDeck).toMatch(/consequence of each choice/iu);
    expect(createDeck).toMatch(/at most one \*\*Recommended\*\* option/iu);
    expect(createDeck).toContain("1A, 2C");
    expect(createDeck).toMatch(/later\s+question should depend on an earlier answer/iu);
    expect(createDeck).toMatch(/objections and proof for a proposal/iu);
    expect(createDeck).toMatch(/working\s+code and migration constraints for a technical update/iu);
    expect(createDeck).toMatch(/uncertainty and comparison for a data story/iu);
    expect(createDeck).toMatch(/workflow and differentiation for a product demo/iu);
    expect(createDeck).toMatch(/emotional shift and narrative anchor for a\s+keynote/iu);
    expect(createDeck).toMatch(/participant activity for a workshop/iu);
    expect(createDeck).toContain("Skip remaining questions — surprise me");
    expect(createDeck.match(/Skip remaining questions — surprise me/gu)).toHaveLength(1);
    expect(createDeck).not.toMatch(/choose the subject too|Or answer “Surprise me”/iu);
    expect(createDeck).toMatch(/visible slide density early/iu);
    expect(createDeck).toMatch(/Density is required/iu);
    expect(createDeck).toMatch(/`concise`[^;]*presenter-led/iu);
    expect(createDeck).toMatch(/`balanced`[^;]*visible evidence/iu);
    expect(createDeck).toMatch(/`detailed`[^;]*reader-led/iu);
    expect(createDeck).toContain("<!-- drever-plan-review-contract:v4 -->");
    expect(createDeck).toMatch(/machine-readable story contract/iu);
    expect(createDeck).toMatch(/valid against the installed\s+version-2 schema/iu);
    expect(createDeck).toMatch(
      /Do not put per-slide density, layout, composition[^.]*motion[^.]*signature\s+moment/iu,
    );
    expect(createDeck).toMatch(
      /deck-wide\s+density plus global direction retained in `brief\.md`/iu,
    );
    expect(createDeck).toMatch(/global canvas[^.]*safe area[^.]*content inset/iu);
    expect(createDeck).toMatch(/human-readable brief and content-only numbered outline/iu);
    expect(createDeck).toMatch(/invite\s+edits or explicit\s+approval,\s+and stop/iu);
    expect(createDeck).toMatch(/exact \*\*Storyboard\*\* URL reported by\s+Drever/iu);
    expect(createDeck).toMatch(/without importing the deck MDX,\s+Theme, or runtime/iu);
    expect(createDeck).toMatch(/skip-remaining escape does not bypass either approval path/iu);
    expect(createDesign).toMatch(/topic-fingerprint test/iu);
    expect(createDesign).toMatch(
      /claim[^→]*→ focal artifact[^→]*→ initial state[^→]*→ meaningful\s+transformation[^→]*→ settled payoff[^→]*→ static or reduced-motion endpoint/iu,
    );
    expect(createDesign).toMatch(/Record each in `art-direction\.md`/iu);
    expect(createDesign).toMatch(/generic fade or slide entrance alone/iu);
    expect(createDesign).toMatch(
      /unchanged focal artifact[^.]*supporting feedback[^.]*not a signature transformation/iu,
    );
    expect(createDesign).toMatch(/recurring\s+Stage path[^.]*subordinate atmosphere/iu);
    expect(createDesign).toMatch(/implementation receipt/iu);
    expect(createDesign).toMatch(/before pixels[^.]*after pixels[^.]*artifact that changes/iu);
    expect(reviewDeck).toMatch(/coherent visual-story arc/iu);
    expect(reviewDeck).toMatch(/passing implementation gate for every planned signature moment/iu);
    expect(reviewDeck).toMatch(/pixel-first verdict/iu);
    expect(reviewDeck.indexOf("pixel-first verdict")).toBeLessThan(
      reviewDeck.indexOf("Only after the pixel-first verdict"),
    );
    expect(reviewDeck).toMatch(/unchanged artifact[^.]*receipt[^.]*fails this gate/iu);
  });

  it("installs a latency-bounded exact Studio question publication contract", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const createDeck = await read(root, ".agents/skills/drever-create-deck/SKILL.md");
    const studioContract = createDeck.slice(
      createDeck.indexOf("<!-- drever-studio-question-contract:v1 -->"),
      createDeck.indexOf("## Resolve the brief"),
    );
    const exampleMatch = studioContract.match(
      /copy this exact structure[^]*?```json\n([^]*?)\n```/iu,
    );

    expect(exampleMatch?.[1]).toBeDefined();
    const example = JSON.parse(exampleMatch?.[1] ?? "null") as Record<string, unknown>;
    expect(decodeStudioAgentState(example)).toEqual(example);
    expect(Object.keys(example)).toEqual([
      "version",
      "phase",
      "handledActionRevision",
      "adaptiveQuestions",
    ]);
    expect(example).toMatchObject({
      phase: "adaptive-questions",
      adaptiveQuestions: [
        {
          options: [{ recommended: true }, {}],
        },
      ],
    });
    expect(studioContract).toMatch(
      /Before doing any other work[^.]*use only[^.]*action's `brief`[^.]*publish[^.]*in one pass/isu,
    );
    expect(studioContract).toMatch(
      /Do not inspect or edit project files[^.]*browse or research[^.]*inspect Drever source or schemas/isu,
    );
    expect(studioContract).toMatch(/phase is exactly `adaptive-questions`/iu);
    expect(studioContract).toMatch(/never on the question/iu);
    expect(studioContract).toMatch(/one mechanical retry/iu);
    expect(studioContract).toMatch(/Do not regenerate the\s+round/iu);
    expect(studioContract).toMatch(/start open-ended debugging/iu);
    expect(studioContract).toMatch(/short activity\s+timeline/iu);
    expect(studioContract).toMatch(/never private chain-of-thought/iu);
    expect(studioContract).toMatch(/concise decision summary/iu);
    expect(studioContract).toMatch(/rather than “thinking” or another generic status/iu);
    expect(studioContract).toMatch(
      /For `submit-common-brief`[^.]*actual question\s+round next[^.]*without a separate progress publication/isu,
    );
    expect(studioContract).toMatch(
      /submit-adaptive-answers` and `skip-remaining-questions`[^.]*latency-sensitive/iu,
    );
    expect(studioContract).toMatch(
      /one bounded semantic pass[\s\S]*?submitted brief and direction[\s\S]*?drever\.plan\.json[\s\S]*?awaiting-approval/iu,
    );
    expect(studioContract).toMatch(/publish\s+`plan-review`/iu);
    expect(studioContract).toMatch(
      /Before that first reviewable\s+Storyboard[^.]*do not browse[^.]*research facts or assets/iu,
    );
    expect(studioContract).toMatch(/uncertain facts[^.]*explicit\s+evidence\s+requirements/iu);
    expect(studioContract).toMatch(
      /Stop this managed child turn at the approval gate[^.]*do\s+not mutate the Storyboard/iu,
    );
    expect(studioContract).toMatch(/Continue\s+factual\s+research[^.]*after `approve-plan`/iu);
    expect(studioContract).toMatch(/managed handoff is not task completion/iu);
    expect(studioContract).toMatch(/keep the development command session and parent task alive/iu);
    expect(studioContract).toMatch(/no topic was supplied[^.]*Studio with an empty Brief/iu);
    expect(studioContract).toMatch(/`--topic <topic>`[^.]*prefilled but not submitted/iu);
    expect(studioContract).toMatch(/do not ask for or mirror the topic in chat first/iu);
    expect(studioContract).toMatch(/`continue`[^.]*parent task[^.]*bypass Studio/iu);
    expect(studioContract).toMatch(/Claude Code[^.]*development Bash\s+task actively supervised/iu);
    expect(studioContract).toMatch(/keep observing the managed session[^.]*`ready`, `error`/iu);
    expect(studioContract).toMatch(/Do not publish a final response from an earlier snapshot/iu);
    expect(studioContract).toMatch(/one-shot or noninteractive host[^.]*do not launch Studio/iu);
  });

  it("installs the preview-first progressive delivery contract", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const agents = await read(root, "AGENTS.md");
    const createDeck = await read(root, ".agents/skills/drever-create-deck/SKILL.md");
    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const authorDeck = await read(root, ".agents/skills/drever-author-deck/SKILL.md");
    const openai = await read(root, ".agents/skills/drever-create-deck/agents/openai.yaml");

    expect(createDeck).toContain("<!-- drever-preview-contract:v7 -->");
    expect(createDeck).toMatch(/Reuse the development server already serving/iu);
    expect(createDeck).toMatch(/first useful preview/iu);
    expect(createDeck).toMatch(/bounded semantic pass[^.]*content-complete Draft 1/iu);
    expect(createDeck).toMatch(/embedded audience\s+iframe[^.]*HMR/iu);
    expect(createDeck).toMatch(/only pre-preview gate[^.]*one source check/iu);
    expect(createDeck).toMatch(/publish `preview` in that same action immediately/iu);
    expect(createDeck).toMatch(/Draft 1 before loading\s+`drever-create-design`/iu);
    expect(createDeck).toMatch(/do not start or restart a second\s+server/iu);
    expect(createDeck).toMatch(/Before that publication[^.]*do not\s+invoke Playwright/iu);
    expect(createDeck).toMatch(/non-blocking update/iu);
    expect(createDeck).toMatch(/continue in the same turn/iu);
    expect(createDeck).toMatch(/isolated\s+Playwright rendered review[^.]*final source/iu);
    expect(createDeck).toMatch(/later mutation invalidates[^.]*evidence/iu);
    expect(createDeck).toMatch(
      /Never use `data:`,\s+`blob:`, or `javascript:` URLs as CSS `@import`/iu,
    );
    expect(createDeck).toMatch(/one\s+production build[^.]*requested PDF export/iu);
    expect(createDeck).toMatch(/begin factual research[^.]*after\s+the preview publication/iu);
    expect(authorDeck).toMatch(/Expose an approved Draft 1 without blocking on polish/iu);
    expect(authorDeck).toMatch(
      /Keep the active Studio server, URL, and embedded audience iframe/iu,
    );
    expect(authorDeck).toMatch(/Run only the source check[^.]*drever check --json/iu);
    expect(authorDeck).toMatch(/Only after the final\s+authored source is stable/iu);
    expect(agents).toMatch(/expose the coherent[^.]*Draft 1 before design refinement/iu);
    expect(agents).toMatch(
      /do not run production builds or duplicate the full rendered preflight/iu,
    );
    expect(createDesign).toMatch(
      /must not delay[^.]*coherent end-to-end content\s+Draft 1[^.]*stable development URL/iu,
    );
    expect(createDesign).toMatch(/Do not make a production build[^.]*first useful preview/iu);
    expect(openai).toMatch(/reviewable brief\.md and drever\.plan\.json story contract/iu);
  });

  it("installs the direct-authoring contract without framework archaeology", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const agents = await read(root, "AGENTS.md");
    const createDeck = await read(root, ".agents/skills/drever-create-deck/SKILL.md");
    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");

    expect(createDeck).toContain("<!-- drever-authoring-scope-contract:v3 -->");
    for (const contents of [agents, createDeck, createDesign]) {
      expect(contents).toMatch(/complete public\s+contract/iu);
      expect(contents).toMatch(/do not (?:search or )?inspect[^.]*Drever[^.]*repository/iu);
      expect(contents).toContain("`node_modules`");
      expect(contents).toMatch(/declarations?(?: files)?/iu);
      expect(contents).toMatch(/official design\s+implementations/iu);
      expect(contents).toMatch(/example\s+decks/iu);
      expect(contents).toMatch(/(?:one|the) named\s+public declaration\s+or\s+guide/iu);
    }
    expect(agents).toMatch(/Do not load every skill before Draft 1/iu);
    expect(createDesign).toMatch(
      /configured MDX entry supports local TypeScript,\s+React,\s+and CSS/iu,
    );
    expect(createDesign).toContain("`speaker-current`");
    expect(createDesign).toContain("`speaker-next`");
    expect(createDesign).toMatch(/Do not scan the official studies/iu);
    expect(createDesign).toMatch(/do not run context[^.]*in-progress deck/iu);
    expect(createDesign).not.toMatch(/Scan all eight studies/iu);
    expect(createDesign).not.toMatch(/packages\/designs\/src\/<study>/u);
  });

  it("locks one visual foundation and keeps official designs reference-only", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const agents = await read(root, "AGENTS.md");
    const createDeck = await read(root, ".agents/skills/drever-create-deck/SKILL.md");
    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const authorDeck = await read(root, ".agents/skills/drever-author-deck/SKILL.md");
    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    expect(createDeck).toContain("<!-- drever-visual-foundation-contract:v1 -->");
    expect(createDesign).toContain("<!-- drever-visual-foundation-contract:v1 -->");
    expect(createDeck).toMatch(/exact[^.]*configured canvas[^.]*safe-area/iu);
    expect(createDeck).toMatch(/never substitute\s+1920 × 1080/iu);
    expect(createDesign).toMatch(/Do not change\s+1600 × 900 to 1920 × 1080/iu);
    expect(reviewDeck).toMatch(/resolved canvas[^.]*exact width and height/iu);

    for (const contents of [agents, createDesign, authorDeck]) {
      expect(contents).toMatch(
        /(?:`@drever\/designs`|official designs|official Themes)[^.]*reference studies/iu,
      );
      expect(contents).toMatch(/only when the user explicitly (?:names|chooses)/iu);
    }
    expect(createDesign).toMatch(/custom[^.]*owns the complete presentation surface/iu);
    expect(createDesign).toMatch(/Never put a custom black surface[^.]*inherited\s+blue rail/iu);
    expect(createDesign).toMatch(
      /Prepare replacement Theme CSS[^.]*while they are still unreferenced/iu,
    );
    expect(createDeck).toMatch(/Do\s+not expose a hybrid frame/iu);
    expect(reviewDeck).toMatch(
      /conflicting starter rail\/background[^.]*blocking contract drift/iu,
    );

    for (const contents of [agents, createDeck, createDesign, authorDeck, reviewDeck]) {
      expect(contents).toMatch(/last-known-good|immutable geometry/iu);
      expect(contents).toMatch(/safe area|safe-area/iu);
      expect(contents).toMatch(/panel padding|content-inset|content inset/iu);
    }
    expect(createDeck).toMatch(/slide 1[^.]*restrained opening/iu);
    expect(createDesign).toMatch(/slide 1[^.]*restrained cover/iu);
    expect(reviewDeck).toMatch(/slide 1[^.]*restrained title or premise/iu);
    expect(createDeck).toMatch(/generic\s+browser-control[^.]*before preview/iu);
    expect(reviewDeck).toMatch(/isolated Playwright browser/iu);
  });

  it("routes new, replacement, and edit scopes through one validation pipeline", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const agents = await read(root, "AGENTS.md");
    const createDeck = await read(root, ".agents/skills/drever-create-deck/SKILL.md");
    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const authorDeck = await read(root, ".agents/skills/drever-author-deck/SKILL.md");
    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");
    const deliverDeck = await read(root, ".agents/skills/drever-deliver-deck/SKILL.md");

    expect(createDeck).toContain("<!-- drever-authoring-scope-contract:v3 -->");
    expect(createDeck).toMatch(/\*\*New:\*\*[^]*Continue with this skill/iu);
    expect(createDeck).toMatch(/\*\*Replacement:\*\*[^]*explicitly asks[^]*plan is approved/iu);
    expect(createDeck).toMatch(/\*\*Edit:\*\*[^]*use the project-local `drever-author-deck`/iu);
    expect(createDeck).toMatch(/do not require a\s+new-plan approval gate/iu);
    expect(createDeck).toMatch(/Never infer replacement/iu);
    expect(agents).toMatch(/new or explicitly replacement-scoped deck uses `drever-create-deck`/iu);
    expect(agents).toMatch(/edit to an authored deck[^.]*does not restart that gate/iu);

    expect(createDeck).toMatch(
      /approve-plan` handoff[^.]*bounded semantic pass[^.]*Draft 1 before loading\s+`drever-create-design`/iu,
    );
    expect(createDeck).toMatch(/load the\s+project-local `drever-create-design`[^.]*refinement/iu);
    expect(createDeck).toMatch(/semantic Studio state as the source of truth/iu);
    expect(createDeck).toMatch(/Vite stdout is quiet[^.]*no HMR line/iu);
    expect(createDeck).toMatch(/no\s+`continue` message is required/iu);

    for (const contents of [createDeck, createDesign, authorDeck, deliverDeck]) {
      expect(contents).not.toContain("drever check --rendered");
    }
    expect(reviewDeck).toContain("drever check --rendered --evidence .drever/review --json");
    expect(reviewDeck).toMatch(/single owner[^.]*exhaustive rendered completion gate/iu);
    expect(deliverDeck).toMatch(/Reuse review evidence[^.]*when no source/iu);
    expect(deliverDeck).toMatch(
      /If evidence is absent or any relevant\s+input changed[^.]*review/iu,
    );
    expect(deliverDeck).toMatch(/drever build --json` once/iu);

    for (const contents of [createDeck, createDesign, authorDeck, reviewDeck, deliverDeck]) {
      expect(contents).toMatch(/mutation invalidates[^.]*evidence/iu);
      expect(contents).toMatch(/cancel[^.]*ignore[^.]*result/iu);
      expect(contents).toMatch(/Never (?:hand off or )?cite\s+stale\s+evidence/iu);
    }
  });

  it("installs the varied transition and design-family contract", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const authorDeck = await read(root, ".agents/skills/drever-author-deck/SKILL.md");
    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    expect(createDesign).toMatch(/seven recolored versions[^.]*are one design,\s+not seven/iu);
    expect(authorDeck).toMatch(/Do not apply native View Transitions to every edge/iu);
    expect(authorDeck).not.toContain("one theme-led whole-slide transition voice");
    expect(reviewDeck).toMatch(
      /Flag both random effects and a View Transition applied to every edge/iu,
    );
    for (const contents of [createDesign, authorDeck, reviewDeck]) {
      expect(contents).toMatch(/explicit[^.]*inline size[^.]*block size[^.]*aspect ratio/iu);
    }
    expect(reviewDeck).toMatch(/grow-then-shrink/iu);
  });

  it("installs content-led scene and presentation typography guidance", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const authorDeck = await read(root, ".agents/skills/drever-author-deck/SKILL.md");
    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    expect(createDesign).toContain("<!-- drever-content-scene-contract:v1 -->");
    expect(createDesign).toMatch(/List or card sequence[^]*deterministic stagger/iu);
    expect(createDesign).toMatch(/Dense text[^]*draw-on highlight/iu);
    expect(createDesign).toMatch(/deterministic card wall, tag field, or slow[^]*row motion/iu);
    expect(createDesign).toMatch(/primary readable content[^]*6–8%/iu);
    expect(createDesign).toMatch(/20–36 CJK characters/iu);
    expect(createDesign).toMatch(/WCAG 2\.2/iu);

    for (const contents of [createDesign, authorDeck, reviewDeck]) {
      expect(contents).toMatch(/Stage root[^.]*stationary|Stage root stays fixed/iu);
      expect(contents).toMatch(/safe area/iu);
      expect(contents).toMatch(/panel padding|inner space/iu);
    }
    expect(authorDeck).toMatch(/Map the dominant content form before choosing an effect/iu);
    expect(reviewDeck).toMatch(/reading job rather than from an effect\s+catalog/iu);
    expect(reviewDeck).toMatch(/full-canvas\s+background[^.]*every navigation edge/iu);
  });

  it("installs motion consequence, text-swap, and intermediate-frame review contracts", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const designReference = await read(
      root,
      ".agents/skills/drever-create-design/references/visual-decision-pass.md",
    );
    const authorDeck = await read(root, ".agents/skills/drever-author-deck/SKILL.md");
    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    expect(designReference).toMatch(
      /start state[^]*semantic verb[^]*settled evidence[^]*reverse\/reduced-motion/iu,
    );
    expect(designReference).toMatch(/If the effect vanishes[^.]*remove it/iu);
    expect(designReference).toMatch(/Arrival owner[^]*exactly one/iu);
    expect(createDesign).toMatch(/exactly one arrival owner for every edge/iu);
    expect(authorDeck).toMatch(/fixed-slot sequential dissolve/iu);
    expect(authorDeck).toMatch(/native slide transition[^.]*must\s+not run/iu);
    expect(reviewDeck).toMatch(/sequential live-DOM dissolve/iu);
    expect(reviewDeck).toMatch(/One edge has one arrival owner/iu);

    for (const contents of [createDesign, authorDeck]) {
      expect(contents).toMatch(/transient cue[^.]*visible consequence/iu);
      expect(contents).toMatch(/persistent artifact[^.]*verified result/iu);
    }
    expect(reviewDeck).toMatch(/transient sweep[^.]*persistent artifact[^.]*verified result/iu);
    expect(reviewDeck).toMatch(/disappears without a visible consequence/iu);
    expect(createDesign).toMatch(/initial frame[^.]*visual midpoint[^.]*settled frame/iu);
    expect(reviewDeck).toMatch(/80 ms image[^.]*early-frame tripwire/iu);
    expect(reviewDeck).toMatch(/destination-side animation[^.]*replay the same entrance/iu);
  });

  it("installs stable Step, active-keyframe, and rendered CSS contracts", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const authorDeck = await read(root, ".agents/skills/drever-author-deck/SKILL.md");
    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    for (const contents of [createDesign, authorDeck]) {
      expect(contents).toMatch(/`Step` as a real DOM wrapper/iu);
      expect(contents).toContain('[data-drever-slide][data-slide-state="active"]');
      expect(contents).toContain('[data-drever-step][data-step-state="active"]');
      expect(contents).toMatch(/exactly one motion owner/iu);
      expect(contents).toMatch(/full-canvas scene[^.]*stable positioned slide-relative root/iu);
      expect(contents).toMatch(/line height,\s+margin,\s+padding,\s+gap,\s+and foreground/iu);
      expect(contents).toMatch(/Theme-owned Markdown\s+margins/iu);
    }

    expect(reviewDeck).toMatch(/Step as a real DOM wrapper/iu);
    expect(reviewDeck).toMatch(/containing block[^.]*absolute descendant[^.]*invariant/iu);
    expect(reviewDeck).toMatch(/inactive mounted slides must not consume them early/iu);
    expect(reviewDeck).toMatch(/computed font size[^.]*margin,\s+padding,\s+gap/iu);
    expect(reviewDeck).toMatch(
      /Source review[^.]*do not count as the Draft 1 rendered refinement/iu,
    );
  });

  it("installs the Drever-managed Playwright evidence gate and advisory typography probe", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    expect(reviewDeck).toContain(
      "npm exec -- drever check --rendered --evidence .drever/review --json",
    );
    expect(reviewDeck).toContain(".drever/review/manifest.json");
    expect(reviewDeck).toMatch(/both labeled contact sheets/iu);
    expect(reviewDeck).toMatch(/targeted full-resolution state images/iu);
    expect(reviewDeck).toMatch(/deterministic 80 ms sample/iu);
    expect(reviewDeck).toMatch(/forward and reverse directions/iu);
    expect(reviewDeck).toMatch(/isolated Playwright Chromium context/iu);
    expect(reviewDeck).not.toMatch(/Chrome DevTools MCP|Agent Browser/iu);
    expect(reviewDeck).not.toMatch(
      /`(?:list_pages|evaluate_script|take_snapshot|take_screenshot|list_console_messages|list_network_requests)`/iu,
    );
    expect(reviewDeck).toContain("Pretext typography probe");
    expect(reviewDeck).toMatch(/predicted and rendered line layout/iu);
    expect(reviewDeck).toMatch(/optional advisory evidence/iu);
    expect(reviewDeck).toMatch(/not part of the required evidence command/iu);
  });

  it("installs the complete kit and reports a stable idempotent result", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("v1");

    const created = await syncAgentKit({ root, templateRoot });

    expect(created.files).toEqual(CODEX_TARGETS.map((path) => ({ path, status: "created" })));
    await expect(read(root, "AGENTS.md")).resolves.toBe(await read(templateRoot, "AGENTS.md"));
    for (const skill of SKILLS) {
      await expect(read(root, `.agents/skills/${skill}/SKILL.md`)).resolves.toBe(
        await read(templateRoot, `skills/${skill}/SKILL.md`),
      );
      await expect(read(root, `.agents/skills/${skill}/agents/openai.yaml`)).resolves.toBe(
        await read(templateRoot, `skills/${skill}/agents/openai.yaml`),
      );
      for (const path of SKILL_RESOURCES[skill] ?? []) {
        await expect(read(root, `.agents/skills/${skill}/${path}`)).resolves.toBe(
          await read(templateRoot, `skills/${skill}/${path}`),
        );
      }
    }

    const unchanged = await syncAgentKit({ root, templateRoot });
    expect(unchanged.files).toEqual(CODEX_TARGETS.map((path) => ({ path, status: "unchanged" })));
  });

  it("preserves user instructions while appending and updating only Drever-owned content", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("v2");
    const userInstructions = "# Project rules\n\nNever edit generated snapshots.\n";
    await write(root, "AGENTS.md", userInstructions);
    await write(
      root,
      ".agents/skills/drever-create-deck/SKILL.md",
      `${SKILL_MARKER}\n\n# Old generated skill\n`,
    );
    const unchangedYaml = await read(templateRoot, "skills/drever-review-deck/agents/openai.yaml");
    await write(root, ".agents/skills/drever-review-deck/agents/openai.yaml", unchangedYaml);

    const first = await syncAgentKit({ root, templateRoot });

    expect(first.files).toEqual([
      { path: "AGENTS.md", status: "updated" },
      { path: ".agents/skills/drever-author-deck/SKILL.md", status: "created" },
      { path: ".agents/skills/drever-author-deck/agents/openai.yaml", status: "created" },
      { path: ".agents/skills/drever-create-deck/SKILL.md", status: "updated" },
      { path: ".agents/skills/drever-create-deck/agents/openai.yaml", status: "created" },
      { path: ".agents/skills/drever-create-design/SKILL.md", status: "created" },
      {
        path: ".agents/skills/drever-create-design/references/visual-decision-pass.md",
        status: "created",
      },
      { path: ".agents/skills/drever-create-design/agents/openai.yaml", status: "created" },
      { path: ".agents/skills/drever-review-deck/SKILL.md", status: "created" },
      { path: ".agents/skills/drever-review-deck/agents/openai.yaml", status: "unchanged" },
      { path: ".agents/skills/drever-deliver-deck/SKILL.md", status: "created" },
      { path: ".agents/skills/drever-deliver-deck/agents/openai.yaml", status: "created" },
    ]);
    const appended = await read(root, "AGENTS.md");
    expect(appended).toBe(
      `${userInstructions}\n${AGENTS_START}\n## Drever agent kit v2\n\nUse the Drever skills.\n${AGENTS_END}\n`,
    );

    await write(
      templateRoot,
      "AGENTS.md",
      `${AGENTS_START}\n## Drever agent kit v3\n${AGENTS_END}\n`,
    );
    await syncAgentKit({ root, templateRoot });

    const updated = await read(root, "AGENTS.md");
    expect(updated).toBe(
      `${userInstructions}\n${AGENTS_START}\n## Drever agent kit v3\n${AGENTS_END}\n`,
    );
    expect(updated.match(/drever-agent-kit:start/gu)).toHaveLength(1);
  });

  it("reports every user-owned conflict before creating or changing any file", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("v1");
    const userInstructions = "# Keep this file byte-for-byte\n";
    await write(root, "AGENTS.md", userInstructions);
    await write(
      root,
      ".agents/skills/drever-author-deck/SKILL.md",
      "# My custom authoring skill\n",
    );
    await write(
      root,
      ".agents/skills/drever-review-deck/agents/openai.yaml",
      "interface:\n  display_name: My review workflow\n",
    );

    let failure: unknown;
    try {
      await syncAgentKit({ root, templateRoot });
    } catch (error) {
      failure = error;
    }

    expect(failure).toBeInstanceOf(DreverCliError);
    expect(failure).toMatchObject({
      code: "DREVER_AGENT_SYNC_CONFLICT",
      details: {
        conflicts: [
          ".agents/skills/drever-author-deck/SKILL.md",
          ".agents/skills/drever-review-deck/agents/openai.yaml",
        ],
      },
    });
    await expect(read(root, "AGENTS.md")).resolves.toBe(userInstructions);
    await expect(read(root, ".agents/skills/drever-author-deck/SKILL.md")).resolves.toBe(
      "# My custom authoring skill\n",
    );
    await expect(read(root, ".agents/skills/drever-create-deck/SKILL.md")).rejects.toMatchObject({
      code: "ENOENT",
    });
  });

  it("treats an incomplete managed block as a conflict instead of rewriting AGENTS.md", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("v1");
    const malformed = `# User instructions\n\n${AGENTS_START}\nIncomplete\n`;
    await write(root, "AGENTS.md", malformed);

    await expect(syncAgentKit({ root, templateRoot })).rejects.toMatchObject({
      code: "DREVER_AGENT_SYNC_CONFLICT",
      details: { conflicts: ["AGENTS.md"] },
    });
    await expect(read(root, "AGENTS.md")).resolves.toBe(malformed);
    await expect(read(root, ".agents/skills/drever-author-deck/SKILL.md")).rejects.toMatchObject({
      code: "ENOENT",
    });
  });

  it("installs canonical skills for Claude without Codex-only metadata", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("claude");

    const created = await syncAgentKit({ root, target: "claude", templateRoot });

    expect(created.files).toEqual(CLAUDE_TARGETS.map((path) => ({ path, status: "created" })));
    await expect(read(root, "CLAUDE.md")).resolves.toBe(await read(templateRoot, "AGENTS.md"));
    await expect(read(root, ".claude/skills/drever-create-deck/SKILL.md")).resolves.toBe(
      await read(templateRoot, "skills/drever-create-deck/SKILL.md"),
    );
    await expect(
      read(root, ".claude/skills/drever-create-deck/agents/openai.yaml"),
    ).rejects.toMatchObject({ code: "ENOENT" });
    await expect(read(root, "AGENTS.md")).rejects.toMatchObject({ code: "ENOENT" });

    const unchanged = await syncAgentKit({ root, target: "claude", templateRoot });
    expect(unchanged.files).toEqual(CLAUDE_TARGETS.map((path) => ({ path, status: "unchanged" })));
  });

  it("installs both adapters atomically and idempotently", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("all");

    const created = await syncAgentKit({ root, target: "all", templateRoot });
    expect(created.files).toEqual(
      [...CODEX_TARGETS, ...CLAUDE_TARGETS].map((path) => ({ path, status: "created" })),
    );

    const unchanged = await syncAgentKit({ root, target: "all", templateRoot });
    expect(unchanged.files).toEqual(
      [...CODEX_TARGETS, ...CLAUDE_TARGETS].map((path) => ({ path, status: "unchanged" })),
    );
  });

  it("auto-detects Claude and keeps Codex as the empty-project default", async () => {
    const codexRoot = await temporaryDirectory("drever-agent-project-");
    const claudeRoot = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("auto");
    await mkdir(join(claudeRoot, ".claude"));

    const codex = await syncAgentKit({ root: codexRoot, target: "auto", templateRoot });
    const claude = await syncAgentKit({ root: claudeRoot, target: "auto", templateRoot });

    expect(codex.files.map(({ path }) => path)).toEqual(CODEX_TARGETS);
    expect(claude.files.map(({ path }) => path)).toEqual(CLAUDE_TARGETS);
  });

  it("does not install either adapter when an all-target sync has a conflict", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("all");
    await write(
      root,
      ".claude/skills/drever-deliver-deck/SKILL.md",
      "# My project delivery workflow\n",
    );

    await expect(syncAgentKit({ root, target: "all", templateRoot })).rejects.toMatchObject({
      code: "DREVER_AGENT_SYNC_CONFLICT",
      details: { conflicts: [".claude/skills/drever-deliver-deck/SKILL.md"] },
    });
    await expect(read(root, "AGENTS.md")).rejects.toMatchObject({ code: "ENOENT" });
    await expect(read(root, "CLAUDE.md")).rejects.toMatchObject({ code: "ENOENT" });
  });
});
