import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, describe, expect, it } from "vite-plus/test";
import { syncAgentKit } from "./agent-sync.ts";
import { DreverCliError } from "./errors.ts";

const AGENTS_START = "<!-- drever-agent-kit:start -->";
const AGENTS_END = "<!-- drever-agent-kit:end -->";
const SKILL_MARKER = "<!-- Generated by `drever agent sync`. -->";
const YAML_MARKER = "# Generated by `drever agent sync`.";
const SKILLS = [
  "drever-author-deck",
  "drever-create-deck",
  "drever-create-design",
  "drever-review-deck",
  "drever-deliver-deck",
] as const;
const CODEX_TARGETS = [
  "AGENTS.md",
  ...SKILLS.flatMap((skill) => [
    `.agents/skills/${skill}/SKILL.md`,
    `.agents/skills/${skill}/agents/openai.yaml`,
  ]),
] as const;
const CLAUDE_TARGETS = [
  "CLAUDE.md",
  ...SKILLS.map((skill) => `.claude/skills/${skill}/SKILL.md`),
] as const;

const directories: string[] = [];

const temporaryDirectory = async (name: string): Promise<string> => {
  const directory = await mkdtemp(join(tmpdir(), name));
  directories.push(directory);
  return directory;
};

const write = async (root: string, path: string, contents: string): Promise<void> => {
  const destination = join(root, path);
  await mkdir(dirname(destination), { recursive: true });
  await writeFile(destination, contents, "utf8");
};

const read = (root: string, path: string): Promise<string> => readFile(join(root, path), "utf8");

const createTemplateKit = async (version: string): Promise<string> => {
  const root = await temporaryDirectory("drever-agent-kit-");
  await write(
    root,
    "AGENTS.md",
    `${AGENTS_START}\n## Drever agent kit ${version}\n\nUse the Drever skills.\n${AGENTS_END}\n`,
  );
  await Promise.all(
    SKILLS.flatMap((skill) => [
      write(
        root,
        `skills/${skill}/SKILL.md`,
        `${SKILL_MARKER}\n---\nname: ${skill}\n---\n\n# ${skill} ${version}\n`,
      ),
      write(
        root,
        `skills/${skill}/agents/openai.yaml`,
        `${YAML_MARKER}\ninterface:\n  display_name: ${skill} ${version}\n`,
      ),
    ]),
  );
  return root;
};

afterEach(async () => {
  await Promise.all(
    directories.splice(0).map((path) => rm(path, { force: true, recursive: true })),
  );
});

describe("agent kit sync", () => {
  it("resolves the bundled kit from the source module", async () => {
    const root = await temporaryDirectory("drever-agent-project-");

    const result = await syncAgentKit({ root });

    expect(result.files).toEqual(CODEX_TARGETS.map((path) => ({ path, status: "created" })));
    await expect(read(root, "AGENTS.md")).resolves.toContain("## Drever presentation authoring");
    await expect(read(root, ".agents/skills/drever-review-deck/SKILL.md")).resolves.toContain(
      "name: drever-review-deck",
    );
    await expect(read(root, ".agents/skills/drever-deliver-deck/SKILL.md")).resolves.toContain(
      "name: drever-deliver-deck",
    );
  });

  it("installs the blocking rendered-readability contract across the authoring workflow", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const installed = new Map<string, string>();
    for (const skill of [
      "drever-create-deck",
      "drever-create-design",
      "drever-author-deck",
      "drever-review-deck",
    ] as const) {
      const contents = await read(root, `.agents/skills/${skill}/SKILL.md`);
      installed.set(skill, contents);
      expect(contents).toMatch(/Every visible authored string is a reading promise/iu);
      expect(contents).toMatch(
        /not\s+immediately legible at\s+presentation distance[^.]*blocking P0 defect/iu,
      );
      expect(contents).toMatch(/ancestor's\s+`color`\s+is not\s+proof/iu);
      expect(contents).toMatch(
        /fully contained within the shape or surface that visually owns it/iu,
      );
      expect(contents).toMatch(/usable inner silhouette[^.]*rectangular bounding box/iu);
    }

    expect(installed.get("drever-create-deck")).toMatch(
      /every slide at Step 0 and every exact authored Step route/iu,
    );
    expect(installed.get("drever-create-design")).toMatch(
      /every slide at Step 0 and every exact Step state/iu,
    );
    expect(installed.get("drever-review-deck")).toMatch(
      /every slide at Step 0 and every exact sparse Step state/iu,
    );
    expect(installed.get("drever-author-deck")).toMatch(
      /every affected exact slide and Step route/iu,
    );
    expect(installed.get("drever-author-deck")).toMatch(
      /Expand the gate to the whole deck[^.]*shared theme/iu,
    );
  });

  it("installs the unified briefing and topic-specific signature contract", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const createDeck = await read(root, ".agents/skills/drever-create-deck/SKILL.md");
    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    expect(createDeck).toContain("<!-- drever-briefing-contract:v2 -->");
    expect(createDeck).toMatch(/topic is missing[^.]*ask for it by itself/iu);
    expect(createDeck).toMatch(/one to three questions per round/iu);
    expect(createDeck).toMatch(/two to four mutually distinct,\s+topic-specific options/iu);
    expect(createDeck).toMatch(/consequence of each option/iu);
    expect(createDeck).toMatch(/at most one option \*\*Recommended\*\*/iu);
    expect(createDeck).toContain("1A, 2C, 3B");
    expect(createDeck).toMatch(/follow-up should depend on an earlier answer/iu);
    expect(createDeck).toMatch(/Decision,\s+proposal,\s+or sales/iu);
    expect(createDeck).toMatch(/Technical update or tutorial/iu);
    expect(createDeck).toMatch(/Research,\s+report,\s+or data story/iu);
    expect(createDeck).toMatch(/Product launch or demo/iu);
    expect(createDeck).toMatch(/Keynote,\s+brand,\s+or narrative/iu);
    expect(createDeck).toMatch(/Workshop or training/iu);
    expect(createDeck).toContain("Skip remaining questions — surprise me");
    expect(createDeck.match(/Skip remaining questions — surprise me/gu)).toHaveLength(1);
    expect(createDeck).not.toMatch(/choose the subject too|Or answer “Surprise me”/iu);
    expect(createDeck).toMatch(/record them in `brief\.md`/iu);
    expect(createDeck).toMatch(/topic-fingerprint test/iu);
    expect(createDeck).toMatch(
      /claim[^→]*→ focal artifact[^→]*→ initial state[^→]*→ meaningful transformation[^→]*→ settled payoff[^→]*→ static or reduced-motion endpoint/iu,
    );
    expect(createDesign).toMatch(/Record each in `art-direction\.md`/iu);
    expect(createDesign).toMatch(/generic fade or slide entrance alone/iu);
    expect(reviewDeck).toMatch(/what one scene the audience will remember/iu);
    expect(reviewDeck).toMatch(/redesign exactly one high-value beat/iu);
  });

  it("installs the varied transition and design-family contract", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const createDeck = await read(root, ".agents/skills/drever-create-deck/SKILL.md");
    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const authorDeck = await read(root, ".agents/skills/drever-author-deck/SKILL.md");
    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    expect(createDeck).toMatch(/do not mistake consistency for one effect on every edge/iu);
    expect(createDesign).toMatch(/seven recolored versions[^.]*are one design,\s+not seven/iu);
    expect(authorDeck).toMatch(/Do not apply native View Transitions to every edge/iu);
    expect(authorDeck).not.toContain("one theme-led whole-slide transition voice");
    expect(reviewDeck).toMatch(
      /Flag both random effects and a View Transition applied to every edge/iu,
    );
    for (const contents of [createDeck, createDesign, authorDeck, reviewDeck]) {
      expect(contents).toMatch(/explicit[^.]*inline size[^.]*block size[^.]*aspect ratio/iu);
    }
    expect(reviewDeck).toMatch(/grow-then-shrink/iu);
  });

  it("installs stable Step, active-keyframe, and rendered CSS contracts", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const createDeck = await read(root, ".agents/skills/drever-create-deck/SKILL.md");
    const createDesign = await read(root, ".agents/skills/drever-create-design/SKILL.md");
    const authorDeck = await read(root, ".agents/skills/drever-author-deck/SKILL.md");
    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    for (const contents of [createDeck, createDesign, authorDeck]) {
      expect(contents).toMatch(/`Step` as a real DOM wrapper/iu);
      expect(contents).toContain('[data-drever-slide][data-slide-state="active"]');
      expect(contents).toContain('[data-drever-step][data-step-state="active"]');
      expect(contents).toMatch(/exactly one motion owner/iu);
      expect(contents).toMatch(/full-canvas scene[^.]*stable positioned slide-relative root/iu);
      expect(contents).toMatch(/line height,\s+margin,\s+padding,\s+gap,\s+and foreground/iu);
      expect(contents).toMatch(/Theme-owned Markdown margins/iu);
    }

    expect(reviewDeck).toMatch(/Step as a real DOM wrapper/iu);
    expect(reviewDeck).toMatch(/containing block[^.]*absolute descendant[^.]*invariant/iu);
    expect(reviewDeck).toMatch(/inactive mounted slides must not consume them early/iu);
    expect(reviewDeck).toMatch(/computed font size[^.]*margin,\s+padding,\s+gap/iu);
    expect(reviewDeck).toMatch(
      /Source review[^.]*do not count as the Draft 1 rendered refinement/iu,
    );
  });

  it("installs the browser-first review gate and advisory typography probe", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    await syncAgentKit({ root });

    const reviewDeck = await read(root, ".agents/skills/drever-review-deck/SKILL.md");

    expect(reviewDeck).toMatch(/Prefer a connected Chrome DevTools MCP server/iu);
    for (const tool of [
      "list_pages",
      "evaluate_script",
      "take_snapshot",
      "take_screenshot",
      "list_console_messages",
      "list_network_requests",
    ]) {
      expect(reviewDeck).toContain(`\`${tool}\``);
    }
    expect(reviewDeck).toContain("globalThis.__dreverExperimentalTextLayout()");
    expect(reviewDeck).toMatch(/uses Pretext[^.]*predicted and rendered line layout/iu);
    expect(reviewDeck).toMatch(/Treat its report as advisory/iu);
    expect(reviewDeck).toMatch(/Rendered DOM and pixels remain authoritative|browser layout/iu);
  });

  it("installs the complete kit and reports a stable idempotent result", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("v1");

    const created = await syncAgentKit({ root, templateRoot });

    expect(created.files).toEqual(CODEX_TARGETS.map((path) => ({ path, status: "created" })));
    await expect(read(root, "AGENTS.md")).resolves.toBe(await read(templateRoot, "AGENTS.md"));
    for (const skill of SKILLS) {
      await expect(read(root, `.agents/skills/${skill}/SKILL.md`)).resolves.toBe(
        await read(templateRoot, `skills/${skill}/SKILL.md`),
      );
      await expect(read(root, `.agents/skills/${skill}/agents/openai.yaml`)).resolves.toBe(
        await read(templateRoot, `skills/${skill}/agents/openai.yaml`),
      );
    }

    const unchanged = await syncAgentKit({ root, templateRoot });
    expect(unchanged.files).toEqual(CODEX_TARGETS.map((path) => ({ path, status: "unchanged" })));
  });

  it("preserves user instructions while appending and updating only Drever-owned content", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("v2");
    const userInstructions = "# Project rules\n\nNever edit generated snapshots.\n";
    await write(root, "AGENTS.md", userInstructions);
    await write(
      root,
      ".agents/skills/drever-create-deck/SKILL.md",
      `${SKILL_MARKER}\n\n# Old generated skill\n`,
    );
    const unchangedYaml = await read(templateRoot, "skills/drever-review-deck/agents/openai.yaml");
    await write(root, ".agents/skills/drever-review-deck/agents/openai.yaml", unchangedYaml);

    const first = await syncAgentKit({ root, templateRoot });

    expect(first.files).toEqual([
      { path: "AGENTS.md", status: "updated" },
      { path: ".agents/skills/drever-author-deck/SKILL.md", status: "created" },
      { path: ".agents/skills/drever-author-deck/agents/openai.yaml", status: "created" },
      { path: ".agents/skills/drever-create-deck/SKILL.md", status: "updated" },
      { path: ".agents/skills/drever-create-deck/agents/openai.yaml", status: "created" },
      { path: ".agents/skills/drever-create-design/SKILL.md", status: "created" },
      { path: ".agents/skills/drever-create-design/agents/openai.yaml", status: "created" },
      { path: ".agents/skills/drever-review-deck/SKILL.md", status: "created" },
      { path: ".agents/skills/drever-review-deck/agents/openai.yaml", status: "unchanged" },
      { path: ".agents/skills/drever-deliver-deck/SKILL.md", status: "created" },
      { path: ".agents/skills/drever-deliver-deck/agents/openai.yaml", status: "created" },
    ]);
    const appended = await read(root, "AGENTS.md");
    expect(appended).toBe(
      `${userInstructions}\n${AGENTS_START}\n## Drever agent kit v2\n\nUse the Drever skills.\n${AGENTS_END}\n`,
    );

    await write(
      templateRoot,
      "AGENTS.md",
      `${AGENTS_START}\n## Drever agent kit v3\n${AGENTS_END}\n`,
    );
    await syncAgentKit({ root, templateRoot });

    const updated = await read(root, "AGENTS.md");
    expect(updated).toBe(
      `${userInstructions}\n${AGENTS_START}\n## Drever agent kit v3\n${AGENTS_END}\n`,
    );
    expect(updated.match(/drever-agent-kit:start/gu)).toHaveLength(1);
  });

  it("reports every user-owned conflict before creating or changing any file", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("v1");
    const userInstructions = "# Keep this file byte-for-byte\n";
    await write(root, "AGENTS.md", userInstructions);
    await write(
      root,
      ".agents/skills/drever-author-deck/SKILL.md",
      "# My custom authoring skill\n",
    );
    await write(
      root,
      ".agents/skills/drever-review-deck/agents/openai.yaml",
      "interface:\n  display_name: My review workflow\n",
    );

    let failure: unknown;
    try {
      await syncAgentKit({ root, templateRoot });
    } catch (error) {
      failure = error;
    }

    expect(failure).toBeInstanceOf(DreverCliError);
    expect(failure).toMatchObject({
      code: "DREVER_AGENT_SYNC_CONFLICT",
      details: {
        conflicts: [
          ".agents/skills/drever-author-deck/SKILL.md",
          ".agents/skills/drever-review-deck/agents/openai.yaml",
        ],
      },
    });
    await expect(read(root, "AGENTS.md")).resolves.toBe(userInstructions);
    await expect(read(root, ".agents/skills/drever-author-deck/SKILL.md")).resolves.toBe(
      "# My custom authoring skill\n",
    );
    await expect(read(root, ".agents/skills/drever-create-deck/SKILL.md")).rejects.toMatchObject({
      code: "ENOENT",
    });
  });

  it("treats an incomplete managed block as a conflict instead of rewriting AGENTS.md", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("v1");
    const malformed = `# User instructions\n\n${AGENTS_START}\nIncomplete\n`;
    await write(root, "AGENTS.md", malformed);

    await expect(syncAgentKit({ root, templateRoot })).rejects.toMatchObject({
      code: "DREVER_AGENT_SYNC_CONFLICT",
      details: { conflicts: ["AGENTS.md"] },
    });
    await expect(read(root, "AGENTS.md")).resolves.toBe(malformed);
    await expect(read(root, ".agents/skills/drever-author-deck/SKILL.md")).rejects.toMatchObject({
      code: "ENOENT",
    });
  });

  it("installs canonical skills for Claude without Codex-only metadata", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("claude");

    const created = await syncAgentKit({ root, target: "claude", templateRoot });

    expect(created.files).toEqual(CLAUDE_TARGETS.map((path) => ({ path, status: "created" })));
    await expect(read(root, "CLAUDE.md")).resolves.toBe(await read(templateRoot, "AGENTS.md"));
    await expect(read(root, ".claude/skills/drever-create-deck/SKILL.md")).resolves.toBe(
      await read(templateRoot, "skills/drever-create-deck/SKILL.md"),
    );
    await expect(
      read(root, ".claude/skills/drever-create-deck/agents/openai.yaml"),
    ).rejects.toMatchObject({ code: "ENOENT" });
    await expect(read(root, "AGENTS.md")).rejects.toMatchObject({ code: "ENOENT" });

    const unchanged = await syncAgentKit({ root, target: "claude", templateRoot });
    expect(unchanged.files).toEqual(CLAUDE_TARGETS.map((path) => ({ path, status: "unchanged" })));
  });

  it("installs both adapters atomically and idempotently", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("all");

    const created = await syncAgentKit({ root, target: "all", templateRoot });
    expect(created.files).toEqual(
      [...CODEX_TARGETS, ...CLAUDE_TARGETS].map((path) => ({ path, status: "created" })),
    );

    const unchanged = await syncAgentKit({ root, target: "all", templateRoot });
    expect(unchanged.files).toEqual(
      [...CODEX_TARGETS, ...CLAUDE_TARGETS].map((path) => ({ path, status: "unchanged" })),
    );
  });

  it("auto-detects Claude and keeps Codex as the empty-project default", async () => {
    const codexRoot = await temporaryDirectory("drever-agent-project-");
    const claudeRoot = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("auto");
    await mkdir(join(claudeRoot, ".claude"));

    const codex = await syncAgentKit({ root: codexRoot, target: "auto", templateRoot });
    const claude = await syncAgentKit({ root: claudeRoot, target: "auto", templateRoot });

    expect(codex.files.map(({ path }) => path)).toEqual(CODEX_TARGETS);
    expect(claude.files.map(({ path }) => path)).toEqual(CLAUDE_TARGETS);
  });

  it("does not install either adapter when an all-target sync has a conflict", async () => {
    const root = await temporaryDirectory("drever-agent-project-");
    const templateRoot = await createTemplateKit("all");
    await write(
      root,
      ".claude/skills/drever-deliver-deck/SKILL.md",
      "# My project delivery workflow\n",
    );

    await expect(syncAgentKit({ root, target: "all", templateRoot })).rejects.toMatchObject({
      code: "DREVER_AGENT_SYNC_CONFLICT",
      details: { conflicts: [".claude/skills/drever-deliver-deck/SKILL.md"] },
    });
    await expect(read(root, "AGENTS.md")).rejects.toMatchObject({ code: "ENOENT" });
    await expect(read(root, "CLAUDE.md")).rejects.toMatchObject({ code: "ENOENT" });
  });
});
