import { lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { DreverCliError } from "./errors.ts";

export type AgentSyncStatus = "created" | "unchanged" | "updated";

export type AgentSyncFileResult = Readonly<{
  path: string;
  status: AgentSyncStatus;
}>;

export type AgentSyncResult = Readonly<{
  files: readonly AgentSyncFileResult[];
}>;

export type SyncAgentKitOptions = Readonly<{
  root: string;
  templateRoot?: string | URL;
}>;

const AGENTS_START = "<!-- drever-agent-kit:start -->";
const AGENTS_END = "<!-- drever-agent-kit:end -->";
const SKILL_MARKER = "<!-- Generated by `drever agent sync`. -->";
const YAML_MARKER = "# Generated by `drever agent sync`.";
const SKILLS = ["drever-author-deck", "drever-create-deck", "drever-review-deck"] as const;

type Target = Readonly<{
  destination: readonly string[];
  marker: string;
  source: readonly string[];
}>;

type ExistingFile = Readonly<
  { contents: string; kind: "file" } | { kind: "missing" } | { kind: "unsupported" }
>;

type PlannedFile = Readonly<{
  contents: string;
  destination: string;
  path: string;
  status: AgentSyncStatus;
}>;

const targets: readonly Target[] = Object.freeze(
  SKILLS.flatMap((skill) => [
    {
      destination: [".agents", "skills", skill, "SKILL.md"],
      marker: SKILL_MARKER,
      source: ["skills", skill, "SKILL.md"],
    },
    {
      destination: [".agents", "skills", skill, "agents", "openai.yaml"],
      marker: YAML_MARKER,
      source: ["skills", skill, "agents", "openai.yaml"],
    },
  ]),
);

const errorCode = (error: unknown): string | undefined =>
  error instanceof Error && "code" in error && typeof error.code === "string"
    ? error.code
    : undefined;

const readExistingFile = async (path: string): Promise<ExistingFile> => {
  try {
    const metadata = await lstat(path);
    if (!metadata.isFile()) {
      return { kind: "unsupported" };
    }
    return { contents: await readFile(path, "utf8"), kind: "file" };
  } catch (error) {
    if (errorCode(error) === "ENOENT") {
      return { kind: "missing" };
    }
    throw error;
  }
};

const readTemplate = async (path: string): Promise<string> => {
  try {
    return await readFile(path, "utf8");
  } catch (cause) {
    throw new DreverCliError(
      "DREVER_AGENT_KIT_INVALID",
      `Could not read the bundled agent template: ${path}`,
      { cause, details: { path } },
    );
  }
};

const managedRange = (contents: string): Readonly<{ end: number; start: number }> | undefined => {
  const start = contents.indexOf(AGENTS_START);
  const endMarker = contents.indexOf(AGENTS_END);
  if (
    start < 0 ||
    endMarker < start ||
    contents.indexOf(AGENTS_START, start + AGENTS_START.length) >= 0 ||
    contents.indexOf(AGENTS_END, endMarker + AGENTS_END.length) >= 0
  ) {
    return;
  }
  return { end: endMarker + AGENTS_END.length, start };
};

const hasEitherManagedMarker = (contents: string): boolean =>
  contents.includes(AGENTS_START) || contents.includes(AGENTS_END);

const appendManagedBlock = (contents: string, block: string): string => {
  if (contents.length === 0) {
    return `${block}\n`;
  }
  const separator = contents.endsWith("\n\n") ? "" : contents.endsWith("\n") ? "\n" : "\n\n";
  return `${contents}${separator}${block}\n`;
};

const planAgentsFile = (
  destination: string,
  existing: ExistingFile,
  template: string,
): PlannedFile | undefined => {
  const templateRange = managedRange(template);
  if (templateRange === undefined) {
    throw new DreverCliError(
      "DREVER_AGENT_KIT_INVALID",
      "The bundled AGENTS.md template must contain one Drever managed block.",
      { details: { path: "AGENTS.md" } },
    );
  }
  if (existing.kind === "unsupported") {
    return;
  }
  if (existing.kind === "missing") {
    return {
      contents: template,
      destination,
      path: "AGENTS.md",
      status: "created",
    };
  }

  const existingRange = managedRange(existing.contents);
  if (existingRange === undefined && hasEitherManagedMarker(existing.contents)) {
    return;
  }
  const block = template.slice(templateRange.start, templateRange.end);
  const contents =
    existingRange === undefined
      ? appendManagedBlock(existing.contents, block)
      : `${existing.contents.slice(0, existingRange.start)}${block}${existing.contents.slice(existingRange.end)}`;
  return {
    contents,
    destination,
    path: "AGENTS.md",
    status: contents === existing.contents ? "unchanged" : "updated",
  };
};

const planOwnedFile = (
  destination: string,
  existing: ExistingFile,
  marker: string,
  path: string,
  template: string,
): PlannedFile | undefined => {
  if (!template.includes(marker)) {
    throw new DreverCliError(
      "DREVER_AGENT_KIT_INVALID",
      `The bundled agent template is missing its ownership marker: ${path}`,
      { details: { path } },
    );
  }
  if (existing.kind === "unsupported") {
    return;
  }
  if (existing.kind === "missing") {
    return { contents: template, destination, path, status: "created" };
  }
  if (existing.contents === template) {
    return { contents: template, destination, path, status: "unchanged" };
  }
  if (!existing.contents.includes(marker)) {
    return;
  }
  return { contents: template, destination, path, status: "updated" };
};

const templateRootPath = (templateRoot: string | URL | undefined): string =>
  typeof templateRoot === "string"
    ? templateRoot
    : fileURLToPath(templateRoot ?? new URL("../agent-kit/", import.meta.url));

/** Installs Drever's agent instructions without replacing user-owned project files. */
export const syncAgentKit = async ({
  root,
  templateRoot,
}: SyncAgentKitOptions): Promise<AgentSyncResult> => {
  const sourceRoot = templateRootPath(templateRoot);
  const agentsDestination = join(root, "AGENTS.md");
  const [agentsTemplate, agentsExisting, skillInputs] = await Promise.all([
    readTemplate(join(sourceRoot, "AGENTS.md")),
    readExistingFile(agentsDestination),
    Promise.all(
      targets.map(async (target) => {
        const [template, existing] = await Promise.all([
          readTemplate(join(sourceRoot, ...target.source)),
          readExistingFile(join(root, ...target.destination)),
        ]);
        return { existing, target, template };
      }),
    ),
  ]);

  const plans: Array<PlannedFile | undefined> = [
    planAgentsFile(agentsDestination, agentsExisting, agentsTemplate),
  ];
  for (const { existing, target, template } of skillInputs) {
    const path = target.destination.join("/");
    plans.push(
      planOwnedFile(join(root, ...target.destination), existing, target.marker, path, template),
    );
  }

  const paths = ["AGENTS.md", ...targets.map((target) => target.destination.join("/"))];
  const conflicts = plans.flatMap((plan, index) =>
    plan === undefined ? [paths[index] as string] : [],
  );
  if (conflicts.length > 0) {
    throw new DreverCliError(
      "DREVER_AGENT_SYNC_CONFLICT",
      `Agent sync found user-owned or malformed targets:\n${conflicts.map((path) => `- ${path}`).join("\n")}`,
      {
        details: { conflicts: Object.freeze(conflicts) },
        hint: "Merge or move the listed files, then run drever agent sync again.",
      },
    );
  }

  const ready = plans.filter((plan): plan is PlannedFile => plan !== undefined);
  for (const plan of ready) {
    if (plan.status === "unchanged") {
      continue;
    }
    await mkdir(dirname(plan.destination), { recursive: true });
    await writeFile(plan.destination, plan.contents, "utf8");
  }

  return Object.freeze({
    files: Object.freeze(ready.map(({ path, status }) => Object.freeze({ path, status }))),
  });
};
