import { lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { DreverCliError } from "./errors.ts";

export type AgentSyncStatus = "created" | "unchanged" | "updated";

export type AgentSyncTarget = "all" | "auto" | "claude" | "codex";

export type AgentSyncFileResult = Readonly<{
  path: string;
  status: AgentSyncStatus;
}>;

export type AgentSyncResult = Readonly<{
  files: readonly AgentSyncFileResult[];
}>;

export type SyncAgentKitOptions = Readonly<{
  root: string;
  target?: AgentSyncTarget;
  templateRoot?: string | URL;
}>;

const AGENTS_START = "<!-- drever-agent-kit:start -->";
const AGENTS_END = "<!-- drever-agent-kit:end -->";
const SKILL_MARKER = "<!-- Generated by `drever agent sync`. -->";
const YAML_MARKER = "# Generated by `drever agent sync`.";
const SKILLS = [
  "drever-author-deck",
  "drever-create-deck",
  "drever-create-design",
  "drever-review-deck",
  "drever-deliver-deck",
] as const;

type AgentPlatform = "claude" | "codex";

type InstructionTarget = Readonly<{
  destination: readonly string[];
  kind: "instructions";
  source: readonly string[];
}>;

type OwnedTarget = Readonly<{
  destination: readonly string[];
  kind: "owned";
  marker: string;
  source: readonly string[];
}>;

type FileTarget = InstructionTarget | OwnedTarget;

type ExistingFile = Readonly<
  { contents: string; kind: "file" } | { kind: "missing" } | { kind: "unsupported" }
>;

type PlannedFile = Readonly<{
  contents: string;
  destination: string;
  path: string;
  status: AgentSyncStatus;
}>;

const instructionTarget = (platform: AgentPlatform): InstructionTarget => ({
  destination: [platform === "codex" ? "AGENTS.md" : "CLAUDE.md"],
  kind: "instructions",
  source: ["AGENTS.md"],
});

const skillTargets = (platform: AgentPlatform): readonly OwnedTarget[] =>
  SKILLS.flatMap((skill) => {
    const root = [platform === "codex" ? ".agents" : ".claude", "skills", skill] as const;
    const skillTarget: OwnedTarget = {
      destination: [...root, "SKILL.md"],
      kind: "owned",
      marker: SKILL_MARKER,
      source: ["skills", skill, "SKILL.md"],
    };
    if (platform === "claude") {
      return [skillTarget];
    }
    return [
      skillTarget,
      {
        destination: [...root, "agents", "openai.yaml"],
        kind: "owned",
        marker: YAML_MARKER,
        source: ["skills", skill, "agents", "openai.yaml"],
      },
    ];
  });

const fileTargets = (platforms: readonly AgentPlatform[]): readonly FileTarget[] =>
  platforms.flatMap((platform) => [instructionTarget(platform), ...skillTargets(platform)]);

const errorCode = (error: unknown): string | undefined =>
  error instanceof Error && "code" in error && typeof error.code === "string"
    ? error.code
    : undefined;

const readExistingFile = async (path: string): Promise<ExistingFile> => {
  try {
    const metadata = await lstat(path);
    if (!metadata.isFile()) {
      return { kind: "unsupported" };
    }
    return { contents: await readFile(path, "utf8"), kind: "file" };
  } catch (error) {
    if (errorCode(error) === "ENOENT") {
      return { kind: "missing" };
    }
    throw error;
  }
};

const pathExists = async (path: string): Promise<boolean> => {
  try {
    await lstat(path);
    return true;
  } catch (error) {
    if (errorCode(error) === "ENOENT") {
      return false;
    }
    throw error;
  }
};

const resolvePlatforms = async (
  root: string,
  target: AgentSyncTarget | undefined,
): Promise<readonly AgentPlatform[]> => {
  if (target === "all") {
    return ["codex", "claude"];
  }
  if (target === "claude" || target === "codex") {
    return [target];
  }
  if (target !== "auto") {
    return ["codex"];
  }

  const [agentsFile, agentsDirectory, claudeFile, claudeDirectory] = await Promise.all([
    pathExists(join(root, "AGENTS.md")),
    pathExists(join(root, ".agents")),
    pathExists(join(root, "CLAUDE.md")),
    pathExists(join(root, ".claude")),
  ]);
  const codex = agentsFile || agentsDirectory;
  const claude = claudeFile || claudeDirectory;
  if (codex && claude) {
    return ["codex", "claude"];
  }
  return claude ? ["claude"] : ["codex"];
};

const readTemplate = async (path: string): Promise<string> => {
  try {
    return await readFile(path, "utf8");
  } catch (cause) {
    throw new DreverCliError(
      "DREVER_AGENT_KIT_INVALID",
      `Could not read the bundled agent template: ${path}`,
      { cause, details: { path } },
    );
  }
};

const managedRange = (contents: string): Readonly<{ end: number; start: number }> | undefined => {
  const start = contents.indexOf(AGENTS_START);
  const endMarker = contents.indexOf(AGENTS_END);
  if (
    start < 0 ||
    endMarker < start ||
    contents.indexOf(AGENTS_START, start + AGENTS_START.length) >= 0 ||
    contents.indexOf(AGENTS_END, endMarker + AGENTS_END.length) >= 0
  ) {
    return;
  }
  return { end: endMarker + AGENTS_END.length, start };
};

const hasEitherManagedMarker = (contents: string): boolean =>
  contents.includes(AGENTS_START) || contents.includes(AGENTS_END);

const appendManagedBlock = (contents: string, block: string): string => {
  if (contents.length === 0) {
    return `${block}\n`;
  }
  const separator = contents.endsWith("\n\n") ? "" : contents.endsWith("\n") ? "\n" : "\n\n";
  return `${contents}${separator}${block}\n`;
};

const planInstructionFile = (
  destination: string,
  existing: ExistingFile,
  path: string,
  template: string,
): PlannedFile | undefined => {
  const templateRange = managedRange(template);
  if (templateRange === undefined) {
    throw new DreverCliError(
      "DREVER_AGENT_KIT_INVALID",
      "The bundled AGENTS.md template must contain one Drever managed block.",
      { details: { path } },
    );
  }
  if (existing.kind === "unsupported") {
    return;
  }
  if (existing.kind === "missing") {
    return {
      contents: template,
      destination,
      path,
      status: "created",
    };
  }

  const existingRange = managedRange(existing.contents);
  if (existingRange === undefined && hasEitherManagedMarker(existing.contents)) {
    return;
  }
  const block = template.slice(templateRange.start, templateRange.end);
  const contents =
    existingRange === undefined
      ? appendManagedBlock(existing.contents, block)
      : `${existing.contents.slice(0, existingRange.start)}${block}${existing.contents.slice(existingRange.end)}`;
  return {
    contents,
    destination,
    path,
    status: contents === existing.contents ? "unchanged" : "updated",
  };
};

const planOwnedFile = (
  destination: string,
  existing: ExistingFile,
  marker: string,
  path: string,
  template: string,
): PlannedFile | undefined => {
  if (!template.includes(marker)) {
    throw new DreverCliError(
      "DREVER_AGENT_KIT_INVALID",
      `The bundled agent template is missing its ownership marker: ${path}`,
      { details: { path } },
    );
  }
  if (existing.kind === "unsupported") {
    return;
  }
  if (existing.kind === "missing") {
    return { contents: template, destination, path, status: "created" };
  }
  if (existing.contents === template) {
    return { contents: template, destination, path, status: "unchanged" };
  }
  if (!existing.contents.includes(marker)) {
    return;
  }
  return { contents: template, destination, path, status: "updated" };
};

const templateRootPath = (templateRoot: string | URL | undefined): string =>
  typeof templateRoot === "string"
    ? templateRoot
    : fileURLToPath(templateRoot ?? new URL("../agent-kit/", import.meta.url));

/** Installs Drever's agent instructions without replacing user-owned project files. */
export const syncAgentKit = async ({
  root,
  target,
  templateRoot,
}: SyncAgentKitOptions): Promise<AgentSyncResult> => {
  const sourceRoot = templateRootPath(templateRoot);
  const targets = fileTargets(await resolvePlatforms(root, target));
  const inputs = await Promise.all(
    targets.map(async (fileTarget) => {
      const [template, existing] = await Promise.all([
        readTemplate(join(sourceRoot, ...fileTarget.source)),
        readExistingFile(join(root, ...fileTarget.destination)),
      ]);
      return { existing, target: fileTarget, template };
    }),
  );

  const plans: Array<PlannedFile | undefined> = [];
  for (const { existing, target: fileTarget, template } of inputs) {
    const path = fileTarget.destination.join("/");
    const destination = join(root, ...fileTarget.destination);
    plans.push(
      fileTarget.kind === "instructions"
        ? planInstructionFile(destination, existing, path, template)
        : planOwnedFile(destination, existing, fileTarget.marker, path, template),
    );
  }

  const paths = targets.map((fileTarget) => fileTarget.destination.join("/"));
  const conflicts = plans.flatMap((plan, index) =>
    plan === undefined ? [paths[index] as string] : [],
  );
  if (conflicts.length > 0) {
    throw new DreverCliError(
      "DREVER_AGENT_SYNC_CONFLICT",
      `Agent sync found user-owned or malformed targets:\n${conflicts.map((path) => `- ${path}`).join("\n")}`,
      {
        details: { conflicts: Object.freeze(conflicts) },
        hint: "Merge or move the listed files, then run drever agent sync again.",
      },
    );
  }

  const ready = plans.filter((plan): plan is PlannedFile => plan !== undefined);
  for (const plan of ready) {
    if (plan.status === "unchanged") {
      continue;
    }
    await mkdir(dirname(plan.destination), { recursive: true });
    await writeFile(plan.destination, plan.contents, "utf8");
  }

  return Object.freeze({
    files: Object.freeze(ready.map(({ path, status }) => Object.freeze({ path, status }))),
  });
};
